using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using SuperApp.Framework.Infrastructure.Json;
using SuperApp.Framework.Infrastructure.Api;
using SuperApp.Framework.Infrastructure.OpenApi;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Http.Resilience;
using Refit;

namespace SuperApp.Framework.Infrastructure.Http.Downstream;

/// <summary>
/// Registers a typed client of another API of the system (a domain service of the experience, or the internal API of another experience's
/// BFF): Refit over <c>IHttpClientFactory</c>, standard resilience and the address from configuration (ADR-0014, ADR-0038).
/// </summary>
/// <remarks>
/// <para>
/// The client interface and its DTOs are generated by Refitter from the callee's committed OpenAPI contract; they are never written by hand.
/// The returned builder must be completed with exactly one way of authenticating the calls:
/// <c>AddUserTokenForwarding</c> (in the user's context, the default) or <c>AddClientCredentialsToken</c> (system call, the exception,
/// ADR-0040).
/// </para>
/// <para>What every client gets:</para>
/// <list type="bullet">
///   <item><description>base address from <c>Downstream:{name}:BaseAddress</c> (in the cluster the Service address, e.g.
///   <c>http://knowledge-api.knowledge.svc.cluster.local:8080</c>; locally <c>http://localhost:5101</c>); a missing or relative address
///   stops the process at startup;</description></item>
///   <item><description>standard resilience (<c>Microsoft.Extensions.Http.Resilience</c>): total and per-attempt timeouts, circuit breaker,
///   and retries <b>only for safe methods</b> (GET, HEAD, OPTIONS); POST, PUT, PATCH and DELETE are never retried, because a retry after a
///   lost answer could repeat a change;</description></item>
///   <item><description>JSON with web defaults and enums as strings, and ISO 8601 dates in paths and query strings
///   (<see cref="DownstreamUrlParameterFormatter"/>), matching the contracts of this system;</description></item>
///   <item><description>an exception handler that turns an unreachable or slow callee into <c>503</c> / <c>504</c> problem responses
///   (<see cref="DownstreamUnavailableExceptionHandler"/>).</description></item>
/// </list>
/// </remarks>
public static class DownstreamApiServiceCollectionExtensions
{
    /// <summary>Registers the Refit client <typeparamref name="TClient"/> for the API configured under <c>Downstream:{name}</c>.</summary>
    /// <example>
    /// <code>
    /// // appsettings: "Downstream": { "Knowledge": { "BaseAddress": "http://knowledge-api.knowledge.svc.cluster.local:8080" } }
    /// builder.Services.AddDownstreamApi&lt;IKnowledgeApi&gt;(builder.Configuration, "Knowledge").AddUserTokenForwarding();
    /// </code>
    /// </example>
    /// <typeparam name="TClient">The Refit interface generated by Refitter from the callee's contract.</typeparam>
    /// <param name="services">The service collection of the host.</param>
    /// <param name="configuration">Application configuration with the <c>Downstream:{name}:BaseAddress</c> value.</param>
    /// <param name="name">Name of the callee in configuration, e.g. <c>Knowledge</c>.</param>
    /// <returns>The client builder, to add the authentication of the calls.</returns>
    /// <exception cref="InvalidOperationException">The base address is missing or not an absolute URI; thrown at startup.</exception>
    public static IHttpClientBuilder AddDownstreamApi<TClient>(this IServiceCollection services, IConfiguration configuration, string name)
        where TClient : class
    {
        services.TryAddEnumerable(ServiceDescriptor.Singleton<IExceptionHandler, DownstreamUnavailableExceptionHandler>());

        // The build-time OpenAPI generator starts the host without configuration; no call is made then (ADR-0009).
        var address = configuration[$"Downstream:{name}:BaseAddress"]
            ?? (BuildTimeDocumentGeneration.IsActive ? "http://localhost/" : null);
        if (!Uri.TryCreate(address, UriKind.Absolute, out var baseAddress))
        {
            throw new InvalidOperationException($"Brak poprawnego adresu Downstream:{name}:BaseAddress.");
        }

        var settings = new RefitSettings(new SystemTextJsonContentSerializer(SerializerOptions))
        {
            UrlParameterFormatter = new DownstreamUrlParameterFormatter(),
        };
        var builder = services
            .AddRefitClient<TClient>(settings)
            .ConfigureHttpClient(client => client.BaseAddress = baseAddress);

        builder.AddStandardResilienceHandler(options => options.Retry.DisableForUnsafeHttpMethods());
        return builder;
    }

    private static readonly JsonSerializerOptions SerializerOptions = CreateSerializerOptions();

    private static JsonSerializerOptions CreateSerializerOptions()
    {
        var options = new JsonSerializerOptions(JsonSerializerDefaults.Web);
        options.Converters.Add(new JsonStringEnumConverter());
        options.TypeInfoResolver = new DefaultJsonTypeInfoResolver().WithAddedModifier(PolymorphicDiscriminatorProperty.RemoveDuplicate);
        return options;
    }
}
