using System.Text.RegularExpressions;
using SuperApp.Cli.Repository;
using SuperApp.Cli.Scaffolding.Editors;

namespace SuperApp.Cli.Scaffolding.Plans;

/// <summary>Plans of <c>add client</c> and <c>remove client</c>: a generated client of a domain service in the BFF of its experience.</summary>
/// <remarks>
/// <para>
/// A BFF calls only the services of its own experience (ADR-0041), so the service must belong to the BFF's experience. The client is
/// generated by Refitter from the committed contract of the service (ADR-0014), which exists only after the service has been built.
/// </para>
/// <para>
/// <c>remove client</c> refuses while code outside <c>Clients/{Service}</c> still uses the client (controllers, composed endpoints) and
/// lists those files: deleting the client would break the build.
/// </para>
/// </remarks>
internal static class ClientPlans
{
    /// <summary>Builds the plan of <c>add client</c>.</summary>
    /// <param name="model">The scanned repository.</param>
    /// <param name="bffName">Experience or BFF name (<c>example</c>, <c>Example</c>, <c>Example.Bff</c>).</param>
    /// <param name="serviceName">Service name.</param>
    /// <returns>The plan.</returns>
    /// <exception cref="ScaffoldException">The BFF or service does not exist, belongs to another experience, or has no contract yet.</exception>
    public static ScaffoldPlan Add(RepositoryModel model, string bffName, string serviceName)
    {
        var (bff, service) = Resolve(model, bffName, serviceName);
        if (service.Experience != bff.Key)
        {
            throw new ScaffoldException($"Service {service.Name} belongs to experience {service.Experience ?? "?"}, not {bff.Key}; a BFF calls only the services of its experience (ADR-0041). Use the internal API of the other experience's BFF instead.");
        }

        var contract = $"{service.Directory}/{service.Name}.Api/openapi/{service.Name}.Api.json";
        if (!model.Files.Exists(contract))
        {
            throw new ScaffoldException($"{contract} does not exist yet; build the service first: dotnet build {SolutionFiles.Slnx}.");
        }

        var name = service.Name;
        var key = service.Key;
        var settings = $"{bff.Directory}/Clients/{name}/{key}.refitter";
        var cluster = $"http://{key}-api.{key}.svc.cluster.local:8080";
        var local = $"http://localhost:{service.ApiPort ?? 5101}";

        return new ScaffoldPlan($"add client --bff {bff.Key} --service {name}",
        [
            new(settings, $"Refitter settings for {contract}", context => [context.Create(settings, BffEditor.RefitterSettings(bff.Name, name), "Refitter settings")]),
            new($"{bff.Directory}/Clients/{name}/Generated", "generate the client (dotnet refitter)", context =>
                [context.Runner.Dotnet("refitter", "--settings-file", settings, "--no-logging")]),
            new($"{bff.Directory}/Program.cs", $"AddDownstreamApi<I{name}Api>(…).AddUserTokenForwarding()", context =>
                [context.Update($"{bff.Directory}/Program.cs", $"client {name}", content => BffEditor.Register(content, bff.Name, name))]),
            new($"{bff.Directory}/appsettings*.json", $"Downstream:{name}:BaseAddress", context =>
            [
                context.Update($"{bff.Directory}/appsettings.json", cluster, content => BffEditor.AddDownstream(content, name, cluster)),
                context.Update($"{bff.Directory}/appsettings.Development.json", local, content => BffEditor.AddDownstream(content, name, local)),
            ]),
            new(ComposeFile.Path, $"address of {name} and dependency of {bff.Key}-bff", context =>
                [context.Update(ComposeFile.Path, $"Downstream__{name}__BaseAddress", content => ComposeEditor.AddDependency(
                    ComposeEditor.AddEnvironment(content, $"{bff.Key}-bff", $"Downstream__{name}__BaseAddress", cluster), $"{bff.Key}-bff", $"{key}-api"))]),
            new(HelmValuesEditor.BffPath(bff.Key), $"downstream {name}", context =>
                [context.Update(HelmValuesEditor.BffPath(bff.Key), $"downstream {name}", content => HelmValuesEditor.AddDownstream(content, name, cluster))]),
        ],
        [
            $"Expose the operations the module needs: controllers in {bff.Directory}/Controllers/{name} relaying with this.ToActionResult(await client.XAsync(...)) (recipe 01, chapter 08).",
            $"For dates without a time zone (DateTime in the service contract) set dateTimeType to System.DateTime in {settings} and regenerate (see SleepDiary).",
            "Build (regenerates the BFF contracts in openapi/), review the diff of the contracts, run dotnet test and dotnet superapp doctor.",
        ]);
    }

    /// <summary>Builds the plan of <c>remove client</c>.</summary>
    /// <param name="model">The scanned repository.</param>
    /// <param name="bffName">Experience or BFF name.</param>
    /// <param name="serviceName">Service name.</param>
    /// <returns>The plan.</returns>
    /// <exception cref="ScaffoldException">The client does not exist or code of the BFF still uses it.</exception>
    public static ScaffoldPlan Remove(RepositoryModel model, string bffName, string serviceName)
    {
        var (bff, service) = Resolve(model, bffName, serviceName);
        var name = service.Name;
        if (!bff.Clients.Contains(name))
        {
            throw new ScaffoldException($"{bff.Project} has no client of {name}.");
        }

        var usage = new Regex($"\\bI{name}Api\\b|\\.Clients\\.{name}\\b", RegexOptions.None, TimeSpan.FromSeconds(1));
        var users = model.Files.Files(bff.Directory, "*.cs")
            .Concat(model.Files.Files($"{bff.Directory}.Tests", "*.cs"))
            .Where(file => !file.StartsWith($"{bff.Directory}/Clients/{name}/", StringComparison.Ordinal) && !file.EndsWith("/Program.cs", StringComparison.Ordinal))
            .Where(file => usage.IsMatch(model.Files.ReadOrEmpty(file)))
            .ToList();
        if (users.Count > 0)
        {
            throw new ScaffoldException($"The client of {name} is still used by: {string.Join(", ", users)}. Remove or change that code first (the public contract of the BFF changes: plan a new version for the module).");
        }

        return new ScaffoldPlan($"remove client --bff {bff.Key} --service {name}",
        [
            new(HelmValuesEditor.BffPath(bff.Key), $"downstream {name}", context =>
                [context.Update(HelmValuesEditor.BffPath(bff.Key), $"downstream {name}", content => HelmValuesEditor.RemoveDownstream(content, name))]),
            new(ComposeFile.Path, $"address of {name} and dependency of {bff.Key}-bff", context =>
                [context.Update(ComposeFile.Path, $"Downstream__{name}__BaseAddress", content => ComposeEditor.RemoveDependency(
                    ComposeEditor.RemoveEnvironment(content, $"{bff.Key}-bff", $"Downstream__{name}__BaseAddress"), $"{bff.Key}-bff", $"{service.Key}-api"))]),
            new($"{bff.Directory}/appsettings*.json", $"Downstream:{name}", context =>
            [
                context.Update($"{bff.Directory}/appsettings.json", name, content => BffEditor.RemoveDownstream(content, name)),
                context.Update($"{bff.Directory}/appsettings.Development.json", name, content => BffEditor.RemoveDownstream(content, name)),
            ]),
            new($"{bff.Directory}/Program.cs", $"AddDownstreamApi<I{name}Api>", context =>
                [context.Update($"{bff.Directory}/Program.cs", $"client {name}", content => BffEditor.Unregister(content, bff.Name, name))]),
            CommonSteps.DeleteDirectories($"{bff.Directory}/Clients/{name}"),
        ],
        [
            "Build (regenerates the BFF contracts; operations of the service disappear from them), run dotnet test and dotnet superapp doctor.",
        ]);
    }

    private static (BffInfo Bff, ServiceInfo Service) Resolve(RepositoryModel model, string bffName, string serviceName)
    {
        var bff = model.Bffs.FirstOrDefault(candidate => string.Equals(candidate.Key, bffName, StringComparison.OrdinalIgnoreCase)
            || string.Equals(candidate.Project, bffName, StringComparison.OrdinalIgnoreCase))
            ?? throw new ScaffoldException($"There is no BFF {bffName} (dotnet superapp list bffs).");
        var service = model.Services.FirstOrDefault(candidate => string.Equals(candidate.Name, serviceName, StringComparison.OrdinalIgnoreCase))
            ?? throw new ScaffoldException($"There is no service {serviceName} (dotnet superapp list services).");
        return (bff, service);
    }
}
