using Knowledge.Domain.Collections;
using SuperApp.Framework.Domain.Results;
using SuperApp.Framework.Domain.ValueObjects;

namespace Knowledge.Domain.Materials.Content;

/// <summary>
/// Identifier of a single node of a material's block content tree (<see cref="Knowledge.Domain.Materials.Content.ContentBlock"/>).
/// </summary>
/// <remarks>
/// <para>
/// A hand-written strongly typed identifier (ADR-0023) wrapping a <see cref="Guid"/>. It exists so that the compiler rejects
/// mix-ups such as passing a <see cref="CollectionId"/> where a <see cref="MaterialId"/> is expected; all Knowledge IDs are
/// <see cref="Guid"/>s underneath and would otherwise be interchangeable.
/// </para>
/// <para>
/// Block IDs are generated by <see cref="Knowledge.Domain.Materials.Content.ContentBuilder"/> and are <b>not stable</b>: every call to <see cref="Knowledge.Domain.Materials.Material.ReplaceContent"/> rebuilds the whole tree with new IDs. Use them only to link a block to its parent (<see cref="Knowledge.Domain.Materials.Content.ContentBlock.ParentBlockId"/>) and its text spans; do not store them outside the material or use them as anchors in clients.
/// </para>
/// <para>
/// Commands and the HTTP API carry the raw <see cref="Guid"/>; handlers convert it with <see cref="Create(Guid)"/>. EF Core,
/// JSON and OpenAPI mappings come from the <c>SuperApp.Framework</c> conventions, no per-type mapping code is needed.
/// Never create an instance with <c>default</c> or <c>new()</c> (analyzer APP002 rejects it): that yields an empty GUID.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// var block = ContentBlock.Create(parent?.Id, index, spec); // gets BlockId.New() internally
/// </code>
/// </example>
public readonly record struct BlockId : IStronglyTypedId<BlockId, Guid>
{
    private BlockId(Guid value) => Value = value;

    /// <inheritdoc />
    public Guid Value { get; }

    /// <inheritdoc />
    public static BlockId New() => new(Guid.CreateVersion7());

    /// <summary>Creates the identifier from an untrusted <see cref="Guid"/> (command data, route values).</summary>
    /// <param name="value">The raw identifier; must not be <see cref="Guid.Empty"/>.</param>
    /// <returns>
    /// The identifier, or a validation error <c>knowledge.block.invalid_id</c> when <paramref name="value"/> is <see cref="Guid.Empty"/>.
    /// The method does not check that the referenced object exists; that is the repository's job.
    /// </returns>
    public static Result<BlockId> Create(Guid value) =>
        value == Guid.Empty ? Error.Validation("knowledge.block.invalid_id", "Niepoprawny identyfikator bloku.") : new BlockId(value);

    /// <inheritdoc />
    public static BlockId FromTrusted(Guid value) => new(value);

    /// <summary>Returns the GUID in its default format, so that logs and interpolated strings show the value instead of the type name.</summary>
    /// <returns>The wrapped <see cref="Guid"/> formatted with <see cref="Guid.ToString()"/>.</returns>
    public override string ToString() => Value.ToString();
}
