apiVersion: v1
kind: Secret
metadata:
  name: migrator-secrets
  namespace: default
type: Opaque
stringData:
  ConnectionStrings__Migrator: "Server=mssql,1433;Database=SuperApp;User Id=superapp_migrator;Password=Dev!Passw0rd1;TrustServerCertificate=True"
---
apiVersion: v1
kind: Secret
metadata:
  name: knowledge-secrets
  namespace: default
type: Opaque
stringData:
  ConnectionStrings__Write: "Server=mssql,1433;Database=SuperApp;User Id=knowledge_app;Password=Dev!Passw0rd1;TrustServerCertificate=True"
  ConnectionStrings__Read: "Server=mssql,1433;Database=SuperApp;User Id=knowledge_app;Password=Dev!Passw0rd1;TrustServerCertificate=True"
  ConnectionStrings__RabbitMq: "amqp://guest:guest@rabbitmq:5672/"
  ConnectionStrings__Redis: "redis:6379"
  Authentication__RequireHttpsMetadata: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: sleepdiary-secrets
  namespace: default
type: Opaque
stringData:
  ConnectionStrings__Write: "Server=mssql,1433;Database=SuperApp;User Id=sleepdiary_app;Password=Dev!Passw0rd1;TrustServerCertificate=True"
  ConnectionStrings__Read: "Server=mssql,1433;Database=SuperApp;User Id=sleepdiary_app;Password=Dev!Passw0rd1;TrustServerCertificate=True"
  ConnectionStrings__RabbitMq: "amqp://guest:guest@rabbitmq:5672/"
  ConnectionStrings__Redis: "redis:6379"
  Authentication__RequireHttpsMetadata: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: example-bff-secrets
  namespace: default
type: Opaque
stringData:
  ConnectionStrings__Redis: "redis:6379"
  Authentication__RequireHttpsMetadata: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-secrets
  namespace: default
type: Opaque
stringData:
  ConnectionStrings__RabbitMq: "amqp://guest:guest@rabbitmq:5672/"
  Analytics__ProjectToken: ""
  Analytics__IdKey: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
  namespace: default
type: Opaque
stringData:
  ConnectionStrings__Gateway: "Server=mssql,1433;Database=SuperApp;User Id=gateway_app;Password=Dev!Passw0rd1;TrustServerCertificate=True"
  ConnectionStrings__Redis: "redis:6379"
  Authentication__ClientSecret: "secret"
  DataProtection__CertificatePassword: "dev-cert-password"
  Authentication__RequireHttpsMetadata: "false"
