<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Framework\SuperApp.Framework.Application\SuperApp.Framework.Application.csproj" />
    <ProjectReference Include="..\Knowledge.Domain\Knowledge.Domain.csproj" />
    <ProjectReference Include="..\Knowledge.Contracts\Knowledge.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Knowledge.Application.Tests" />
    <InternalsVisibleTo Include="Knowledge.IntegrationTests" />
  </ItemGroup>

</Project>
