using System.Globalization;

namespace SuperApp.Cli.Scaffolding.Editors;

/// <summary>Adds scope constants to the <c>{Service}Scopes</c> class generated by the service template (ADR-0012).</summary>
/// <remarks>
/// A scope <c>invoice.read</c> of the service <c>billing</c> becomes <c>public const string InvoiceRead = Prefix + "invoice.read";</c>,
/// the form the template documents, or <c>"billing.invoice.read"</c> in a class that spells out full literals and has no <c>Prefix</c>. Its XML summary names the scope and ends with a TODO: what the scope allows is a domain decision the
/// tool cannot make, and the documentation rules require it (ADR-0033).
/// </remarks>
internal static class ScopesEditor
{
    /// <summary>Adds constants for scopes that are not declared yet.</summary>
    /// <param name="content">Content of <c>{Service}Scopes.cs</c>.</param>
    /// <param name="key">Lower-case service name, the scope prefix without the dot.</param>
    /// <param name="scopes">Scopes without the prefix, e.g. <c>invoice.read</c>.</param>
    /// <returns>The new content.</returns>
    /// <exception cref="ScaffoldException">The class has no closing brace to insert before.</exception>
    public static string AddConstants(string content, string key, IEnumerable<string> scopes)
    {
        var missing = scopes.Where(scope => !content.Contains($"\"{scope}\"", StringComparison.Ordinal)
            && !content.Contains($"\"{key}.{scope}\"", StringComparison.Ordinal)).ToList();
        if (missing.Count == 0)
        {
            return content;
        }

        var lines = TextEdits.Lines(content);
        var close = lines.FindLastIndex(line => line == "}");
        if (close < 0)
        {
            throw new ScaffoldException("Cannot find the end of the scopes class; add the constants by hand.");
        }

        // Services from the template declare "Prefix + ..."; older services (Knowledge) spell out full literals: follow the file.
        var usesPrefix = content.Contains("const string Prefix = ", StringComparison.Ordinal);

        var added = missing.SelectMany(scope => (string[])
        [
            string.Empty,
            $"    /// <summary>Scope <c>{key}.{scope}</c>. TODO: describe what it allows, for whom and which use cases require it.</summary>",
            usesPrefix
                ? $"    public const string {ConstantName(scope)} = Prefix + \"{scope}\";"
                : $"    public const string {ConstantName(scope)} = \"{key}.{scope}\";",
        ]);
        lines.InsertRange(close, added);
        return TextEdits.Join(lines, content);
    }

    /// <summary>Removes the constant of a scope with its summary line.</summary>
    /// <param name="content">Content of <c>{Service}Scopes.cs</c>.</param>
    /// <param name="scope">Scope without the service prefix.</param>
    /// <returns>The new content.</returns>
    public static string RemoveConstant(string content, string scope)
    {
        var lines = TextEdits.Lines(content);
        var index = lines.FindIndex(line => line.Contains($"\"{scope}\"", StringComparison.Ordinal) && line.Contains("const string", StringComparison.Ordinal));
        if (index < 0)
        {
            return content;
        }

        var start = index;
        while (start > 0 && lines[start - 1].TrimStart().StartsWith("///", StringComparison.Ordinal))
        {
            start--;
        }

        if (start > 0 && lines[start - 1].Length == 0)
        {
            start--;
        }

        lines.RemoveRange(start, index - start + 1);
        return TextEdits.Join(lines, content);
    }

    /// <summary>Returns the constant name of a scope: <c>invoice.read</c> → <c>InvoiceRead</c>.</summary>
    /// <param name="scope">Scope without the service prefix.</param>
    /// <returns>The PascalCase name.</returns>
    public static string ConstantName(string scope) =>
        string.Concat(scope.Split('.', '_').Where(part => part.Length > 0).Select(part => char.ToUpper(part[0], CultureInfo.InvariantCulture) + part[1..]));
}
