<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Framework\SuperApp.Framework.Infrastructure\SuperApp.Framework.Infrastructure.csproj" />
    <ProjectReference Include="..\ServiceName.Application\ServiceName.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ServiceName.IntegrationTests" />
  </ItemGroup>

</Project>
