using Knowledge.Domain.Collections;
using SuperApp.Framework.Domain.Results;
using SuperApp.Framework.Domain.ValueObjects;

namespace Knowledge.Domain.Materials;

/// <summary>
/// Identifier of a material: an article, video or podcast (<see cref="Knowledge.Domain.Materials.Material"/>).
/// </summary>
/// <remarks>
/// <para>
/// A hand-written strongly typed identifier (ADR-0023) wrapping a <see cref="Guid"/>. It exists so that the compiler rejects
/// mix-ups such as passing a <see cref="CollectionId"/> where a <see cref="MaterialId"/> is expected; all Knowledge IDs are
/// <see cref="Guid"/>s underneath and would otherwise be interchangeable.
/// </para>
/// <para>
/// Generated by <see cref="Knowledge.Domain.Materials.Material.Create"/>. Referenced by collection items (<see cref="Knowledge.Domain.Collections.CollectionItem"/>), completions (<see cref="Knowledge.Domain.Library.Completions.MaterialCompletion"/>) and, as a plain <see cref="Guid"/>, by favorites (<see cref="Knowledge.Domain.Library.Favorites.Favorite.ItemId"/>). Carried as <see cref="Guid"/> in the integration events of <c>Knowledge.Contracts</c>.
/// </para>
/// <para>
/// Commands and the HTTP API carry the raw <see cref="Guid"/>; handlers convert it with <see cref="Create(Guid)"/>. EF Core,
/// JSON and OpenAPI mappings come from the <c>SuperApp.Framework</c> conventions, no per-type mapping code is needed.
/// Never create an instance with <c>default</c> or <c>new()</c> (analyzer APP002 rejects it): that yields an empty GUID.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// if (!MaterialId.Create(command.MaterialId).TryGetValue(out var materialId, out _)
///     || !await materials.IsPublishedAsync(materialId, cancellationToken))
/// {
///     return LibraryErrors.ItemNotAvailable;
/// }
/// </code>
/// </example>
public readonly record struct MaterialId : IStronglyTypedId<MaterialId, Guid>
{
    private MaterialId(Guid value) => Value = value;

    /// <inheritdoc />
    public Guid Value { get; }

    /// <inheritdoc />
    public static MaterialId New() => new(Guid.CreateVersion7());

    /// <summary>Creates the identifier from an untrusted <see cref="Guid"/> (command data, route values).</summary>
    /// <param name="value">The raw identifier; must not be <see cref="Guid.Empty"/>.</param>
    /// <returns>
    /// The identifier, or a validation error <c>knowledge.material.invalid_id</c> when <paramref name="value"/> is <see cref="Guid.Empty"/>.
    /// The method does not check that the referenced object exists; that is the repository's job.
    /// </returns>
    public static Result<MaterialId> Create(Guid value) =>
        value == Guid.Empty ? Error.Validation("knowledge.material.invalid_id", "Niepoprawny identyfikator materiału.") : new MaterialId(value);

    /// <inheritdoc />
    public static MaterialId FromTrusted(Guid value) => new(value);

    /// <summary>Returns the GUID in its default format, so that logs and interpolated strings show the value instead of the type name.</summary>
    /// <returns>The wrapped <see cref="Guid"/> formatted with <see cref="Guid.ToString()"/>.</returns>
    public override string ToString() => Value.ToString();
}
