using SuperApp.Framework.Infrastructure.Api;
using Example.Bff.Clients.SleepDiary;
using Microsoft.AspNetCore.Mvc;
using System.Net.Mime;

namespace Example.Bff.Controllers.SleepDiary;

/// <summary>
/// Public API of the Example experience for <c>SleepEntries</c> of the SleepDiary service: the module calls these endpoints, and the
/// BFF passes each call on to the SleepDiary service with the user's token (ADR-0038, ADR-0039, ADR-0040).
/// </summary>
/// <remarks>
/// Pass-through endpoints: request and response bodies are the service's contract types generated by Refitter, and the service's
/// answer, including its error status and <c>code</c>, is relayed unchanged (<c>DownstreamResponseExtensions</c>). Authorization
/// (scopes, resource rules) is decided by the SleepDiary service. When the service cannot be reached the BFF answers
/// <c>503 downstream.unavailable</c> or <c>504 downstream.timeout</c>.
/// </remarks>
/// <param name="sleepDiary">Client of the SleepDiary service, generated from its committed OpenAPI contract.</param>
[ApiController]
[Tags("SleepDiary – SleepEntries")]
public sealed class SleepDiarySleepEntriesController(ISleepDiaryApi sleepDiary) : ControllerBase
{
    /// <summary>Returns the caller's diary entries in a date range, with the average sleep time and quality.</summary>
    /// <remarks>
    /// Required scope: <c>sleepdiary.entry.read</c>. The range is inclusive on both ends, matched against the entry date, and may cover at most
    /// 366 days. Days without an entry are omitted and do not affect the averages.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="from">First day of the range (inclusive), <c>YYYY-MM-DD</c>.</param>
    /// <param name="to">Last day of the range (inclusive), <c>YYYY-MM-DD</c>; not earlier than from and at most 365 days after it.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="200">The diary for the range; <c>entries</c> is empty and both averages are <c>null</c> when there are no entries.</response>
    /// <response code="400">
    /// Invalid range (<c>validation.failed</c>): to is before from or the range is longer than 366 days.
    /// A date that is not in the <c>YYYY-MM-DD</c> format is rejected by the framework with a validation problem with <c>code</c> <c>request.malformed</c> (ADR-0044).
    /// </response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">
    /// The token lacks the scope <c>sleepdiary.entry.read</c> (<c>auth.missing_scope</c>) or does not identify a user (<c>auth.unauthenticated</c>).
    /// </response>
    [HttpGet("v1/sleepdiary/entries")]
    [ProducesResponseType<SleepDiaryDto>(StatusCodes.Status200OK, MediaTypeNames.Application.Json)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> List([FromQuery] System.DateOnly? from, [FromQuery] System.DateOnly? to, CancellationToken cancellationToken) =>
        this.ToActionResult(await sleepDiary.SleepEntriesListAsync(from, to, cancellationToken));

    /// <summary>Returns the caller's diary entry for one day.</summary>
    /// <remarks>Required scope: <c>sleepdiary.entry.read</c>.</remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="date">Entry date (the day the user woke up), <c>YYYY-MM-DD</c>.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="200">The entry for the day.</response>
    /// <response code="400">The date is not in the <c>YYYY-MM-DD</c> format.</response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">
    /// The token lacks the scope <c>sleepdiary.entry.read</c> (<c>auth.missing_scope</c>) or does not identify a user (<c>auth.unauthenticated</c>).
    /// </response>
    /// <response code="404">The caller has no entry for this day (<c>sleepdiary.entry.not_found</c>).</response>
    [HttpGet("v1/sleepdiary/entries/{date}")]
    [ProducesResponseType<SleepEntryDto>(StatusCodes.Status200OK, MediaTypeNames.Application.Json)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status404NotFound, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> Get(System.DateOnly date, CancellationToken cancellationToken) =>
        this.ToActionResult(await sleepDiary.SleepEntriesGetAsync(date, cancellationToken));

    /// <summary>Records a new diary entry for the given day.</summary>
    /// <remarks>
    /// Required scope: <c>sleepdiary.entry.write</c>. One entry per day: to change an existing entry use <c>PUT</c>. The date may be at most
    /// one day after today in UTC (tolerance for time zones ahead of UTC). Time in bed and sleep time (time in bed minus the time to fall asleep)
    /// are computed by the service. Recording an entry publishes the integration event <c>SleepEntryRecordedV1</c> for other services.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="date">Entry date (the day the user woke up), <c>YYYY-MM-DD</c>.</param>
    /// <param name="body">The night's data.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="201">The entry was recorded; the body contains its identifier.</response>
    /// <response code="400">
    /// Invalid data. <c>validation.failed</c>: quality outside 1–5, awakenings outside 0–50, negative time to fall asleep, note longer than
    /// 2000 characters. A malformed date or body is rejected by the framework with a validation problem with <c>code</c> <c>request.malformed</c> (ADR-0044).
    /// Business rules: <c>sleepdiary.entry.future_date</c> (date too far in the future),
    /// <c>sleepdiary.entry.wake_before_bed</c> (wake-up not after bedtime), <c>sleepdiary.entry.wake_date_mismatch</c> (wake-up day differs
    /// from the entry date), <c>sleepdiary.entry.too_long</c> (more than 24 hours in bed), <c>sleepdiary.entry.invalid_latency</c>
    /// (time to fall asleep longer than the time in bed).
    /// </response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">
    /// The token lacks the scope <c>sleepdiary.entry.write</c> (<c>auth.missing_scope</c>) or does not identify a user (<c>auth.unauthenticated</c>).
    /// </response>
    /// <response code="409">The caller already has an entry for this day (<c>sleepdiary.entry.already_exists</c>).</response>
    [HttpPost("v1/sleepdiary/entries/{date}")]
    [ProducesResponseType<CreatedResponse>(StatusCodes.Status201Created, MediaTypeNames.Application.Json)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status409Conflict, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> Record(System.DateOnly date, [FromBody] SleepEntryRequest body, CancellationToken cancellationToken) =>
        this.ToActionResult(await sleepDiary.SleepEntriesRecordAsync(date, body, cancellationToken));

    /// <summary>Replaces all data of the caller's existing diary entry for the given day.</summary>
    /// <remarks>
    /// Required scope: <c>sleepdiary.entry.write</c>. A full replacement: every field is overwritten and an omitted or blank note removes the
    /// existing one. The entry date cannot be changed; delete the entry and record a new one instead. Computed values are recalculated.
    /// No integration event is published. When the request is rejected the entry stays unchanged.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="date">Entry date (the day the user woke up), <c>YYYY-MM-DD</c>.</param>
    /// <param name="body">The new data of the night.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="204">The entry was updated.</response>
    /// <response code="400">
    /// Invalid data. <c>validation.failed</c>: quality outside 1–5, awakenings outside 0–50, negative time to fall asleep, note longer than
    /// 2000 characters. A malformed date or body is rejected by the framework with a validation problem with <c>code</c> <c>request.malformed</c> (ADR-0044). Business rules: <c>sleepdiary.entry.wake_before_bed</c>,
    /// <c>sleepdiary.entry.wake_date_mismatch</c>, <c>sleepdiary.entry.too_long</c>, <c>sleepdiary.entry.invalid_latency</c>.
    /// </response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">
    /// The token lacks the scope <c>sleepdiary.entry.write</c> (<c>auth.missing_scope</c>) or does not identify a user (<c>auth.unauthenticated</c>).
    /// </response>
    /// <response code="404">The caller has no entry for this day (<c>sleepdiary.entry.not_found</c>).</response>
    /// <response code="409">
    /// The entry was changed by another request between reading and saving (<c>persistence.concurrency_conflict</c>);
    /// reload it and retry.
    /// </response>
    [HttpPut("v1/sleepdiary/entries/{date}")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status404NotFound, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status409Conflict, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> Update(System.DateOnly date, [FromBody] SleepEntryRequest body, CancellationToken cancellationToken) =>
        this.ToActionResult(await sleepDiary.SleepEntriesUpdateAsync(date, body, cancellationToken));

    /// <summary>Permanently deletes the caller's diary entry for the given day.</summary>
    /// <remarks>
    /// Required scope: <c>sleepdiary.entry.write</c>. A new entry can be recorded for the same day afterwards. Other services are not notified.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="date">Entry date (the day the user woke up), <c>YYYY-MM-DD</c>.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="204">The entry was deleted.</response>
    /// <response code="400">The date is not in the <c>YYYY-MM-DD</c> format.</response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">
    /// The token lacks the scope <c>sleepdiary.entry.write</c> (<c>auth.missing_scope</c>) or does not identify a user (<c>auth.unauthenticated</c>).
    /// </response>
    /// <response code="404">The caller has no entry for this day (<c>sleepdiary.entry.not_found</c>).</response>
    /// <response code="409">
    /// The entry was changed by another request between reading and saving (<c>persistence.concurrency_conflict</c>);
    /// reload it and retry.
    /// </response>
    [HttpDelete("v1/sleepdiary/entries/{date}")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status404NotFound, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status409Conflict, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> Delete(System.DateOnly date, CancellationToken cancellationToken) =>
        this.ToActionResult(await sleepDiary.SleepEntriesDeleteAsync(date, cancellationToken));
}
