using SuperApp.Framework.Infrastructure.Api;
using Example.Bff.Clients.Knowledge;
using Microsoft.AspNetCore.Mvc;
using System.Net.Mime;

namespace Example.Bff.Controllers.Knowledge;

/// <summary>
/// Public API of the Example experience for <c>Collections</c> of the Knowledge service: the module calls these endpoints, and the
/// BFF passes each call on to the Knowledge service with the user's token (ADR-0038, ADR-0039, ADR-0040).
/// </summary>
/// <remarks>
/// Pass-through endpoints: request and response bodies are the service's contract types generated by Refitter, and the service's
/// answer, including its error status and <c>code</c>, is relayed unchanged (<c>DownstreamResponseExtensions</c>). Authorization
/// (scopes, resource rules) is decided by the Knowledge service. When the service cannot be reached the BFF answers
/// <c>503 downstream.unavailable</c> or <c>504 downstream.timeout</c>.
/// </remarks>
/// <param name="knowledge">Client of the Knowledge service, generated from its committed OpenAPI contract.</param>
[ApiController]
[Tags("Knowledge – Collections")]
public sealed class KnowledgeCollectionsController(IKnowledgeApi knowledge) : ControllerBase
{
    /// <summary>Returns a page of published collections, newest first, optionally limited to one category.</summary>
    /// <remarks>
    /// Required scope: <c>knowledge.catalog.read</c>. Only collections in status <c>Published</c> are returned, ordered by publication
    /// date descending. For readers the material count includes only published materials, the ones they can open; for editors
    /// (scope <c>knowledge.catalog.write</c>) it includes every material of the collection.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="categoryId">Optional filter: only collections assigned to this category. An unknown category yields an empty page.</param>
    /// <param name="page">Page number starting at 1; values lower than 1 are treated as 1.</param>
    /// <param name="pageSize">Page size, 20 by default, clamped to the range 1–100.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="200">The requested page (possibly empty).</response>
    /// <response code="400">
    /// A query parameter has an invalid format (<c>categoryId</c> is not a GUID, or <c>page</c> or <c>pageSize</c> is not an integer);
    /// rejected by the framework with a validation problem with <c>code</c> <c>request.malformed</c> (ADR-0044).
    /// </response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">The token lacks the scope <c>knowledge.catalog.read</c> (<c>auth.missing_scope</c>).</response>
    [HttpGet("v1/knowledge/collections")]
    [ProducesResponseType<PagedResultOfCollectionSummaryDto>(StatusCodes.Status200OK, MediaTypeNames.Application.Json)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> List([FromQuery] System.Guid? categoryId, [FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken) =>
        this.ToActionResult(await knowledge.CollectionsListAsync(categoryId, page, pageSize, cancellationToken));

    /// <summary>Creates a new collection in status <c>Draft</c>, without materials and categories.</summary>
    /// <remarks>
    /// Required scope: <c>knowledge.catalog.write</c> (editor). Title: required, at most 200 characters; description: optional, at most
    /// 2000 characters (both trimmed; a blank description is stored as none). Add materials with <c>PUT /v1/collections/{id}/items</c>
    /// before publishing.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="body">Title and optional description of the collection.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="201">The collection was created; the body contains its identifier.</response>
    /// <response code="400">
    /// Invalid title or description (<c>validation.failed</c>, <c>knowledge.collection.invalid_title</c>,
    /// <c>knowledge.collection.invalid_description</c>).
    /// </response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">The token lacks the scope <c>knowledge.catalog.write</c> (<c>auth.missing_scope</c>).</response>
    [HttpPost("v1/knowledge/collections")]
    [ProducesResponseType<CreatedResponse>(StatusCodes.Status201Created, MediaTypeNames.Application.Json)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> Create([FromBody] CreateCollection body, CancellationToken cancellationToken) =>
        this.ToActionResult(await knowledge.CollectionsCreateAsync(body, cancellationToken));

    /// <summary>Returns the details of a collection with its materials in the collection's order.</summary>
    /// <remarks>
    /// Required scope: <c>knowledge.catalog.read</c>. A reader sees only a published collection and only its published materials
    /// (materials that are drafts or archived are left out of the list). An editor (scope <c>knowledge.catalog.write</c>) sees the
    /// collection and all its materials in every status.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="collectionId">Identifier of the collection.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="200">The collection details.</response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">The token lacks the scope <c>knowledge.catalog.read</c> (<c>auth.missing_scope</c>).</response>
    /// <response code="404">
    /// The collection does not exist or is not visible to the caller, e.g. a draft requested by a reader (<c>knowledge.collection.not_found</c>).
    /// </response>
    [HttpGet("v1/knowledge/collections/{collectionId:guid}")]
    [ProducesResponseType<CollectionDetailsDto>(StatusCodes.Status200OK, MediaTypeNames.Application.Json)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status404NotFound, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> Get(System.Guid collectionId, CancellationToken cancellationToken) =>
        this.ToActionResult(await knowledge.CollectionsGetAsync(collectionId, cancellationToken));

    /// <summary>Changes the title and description of a collection.</summary>
    /// <remarks>
    /// Required scope: <c>knowledge.catalog.write</c> (editor). Title: required, at most 200 characters; description: optional
    /// (<c>null</c> removes it), at most 2000 characters. Allowed in status <c>Draft</c> and <c>Published</c>; an archived collection
    /// cannot be changed.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="collectionId">Identifier of the collection.</param>
    /// <param name="body">The new title and description.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="204">The details were changed.</response>
    /// <response code="400">
    /// Invalid title, description or an empty identifier (<c>validation.failed</c>, <c>knowledge.collection.invalid_title</c>,
    /// <c>knowledge.collection.invalid_description</c>).
    /// </response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">The token lacks the scope <c>knowledge.catalog.write</c> (<c>auth.missing_scope</c>).</response>
    /// <response code="404">The collection does not exist (<c>knowledge.collection.not_found</c>).</response>
    /// <response code="409">
    /// The collection was changed by another request between reading and saving (<c>persistence.concurrency_conflict</c>);
    /// reload it and retry.
    /// </response>
    /// <response code="422">The collection is archived (<c>knowledge.collection.archived</c>).</response>
    [HttpPut("v1/knowledge/collections/{collectionId:guid}")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status404NotFound, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status409Conflict, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status422UnprocessableEntity, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> UpdateDetails(System.Guid collectionId, [FromBody] UpdateCollectionDetailsRequest body, CancellationToken cancellationToken) =>
        this.ToActionResult(await knowledge.CollectionsUpdateDetailsAsync(collectionId, body, cancellationToken));

    /// <summary>Replaces the list of materials in a collection; the order of the list is the order in the collection.</summary>
    /// <remarks>
    /// Required scope: <c>knowledge.catalog.write</c> (editor). At most 200 materials, each at most once; all of them must exist
    /// (in any status: drafts may be added and are hidden from readers until published). A published collection cannot be emptied.
    /// An archived collection cannot be changed.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="collectionId">Identifier of the collection.</param>
    /// <param name="body">The ordered list of material identifiers.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="204">The materials of the collection were set.</response>
    /// <response code="400">
    /// Validation error: missing list or empty identifiers (<c>validation.failed</c>), unknown materials
    /// (<c>knowledge.collection.unknown_materials</c>), too many materials (<c>knowledge.collection.too_many_items</c>)
    /// or duplicates (<c>knowledge.collection.duplicate_items</c>).
    /// </response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">The token lacks the scope <c>knowledge.catalog.write</c> (<c>auth.missing_scope</c>).</response>
    /// <response code="404">The collection does not exist (<c>knowledge.collection.not_found</c>).</response>
    /// <response code="409">
    /// The collection was changed by another request between reading and saving (<c>persistence.concurrency_conflict</c>);
    /// reload it and retry. Two editors replacing the items at the same moment can also get <c>persistence.duplicate</c>.
    /// </response>
    /// <response code="422">
    /// The collection is archived (<c>knowledge.collection.archived</c>), or it is published and the list is empty
    /// (<c>knowledge.collection.items_required</c>).
    /// </response>
    [HttpPut("v1/knowledge/collections/{collectionId:guid}/items")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status404NotFound, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status409Conflict, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status422UnprocessableEntity, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> SetItems(System.Guid collectionId, [FromBody] SetCollectionItemsRequest body, CancellationToken cancellationToken) =>
        this.ToActionResult(await knowledge.CollectionsSetItemsAsync(collectionId, body, cancellationToken));

    /// <summary>Replaces the set of categories of a collection.</summary>
    /// <remarks>
    /// Required scope: <c>knowledge.catalog.write</c> (editor). At most 20 distinct categories, all of which must exist; duplicates in the
    /// request are ignored and an empty list removes all assignments. An archived collection cannot be changed.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="collectionId">Identifier of the collection.</param>
    /// <param name="body">Identifiers of the categories.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="204">The categories of the collection were set.</response>
    /// <response code="400">
    /// Validation error: missing list or empty identifiers (<c>validation.failed</c>), unknown categories (<c>knowledge.category.unknown</c>)
    /// or too many categories (<c>knowledge.collection.too_many_categories</c>).
    /// </response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">The token lacks the scope <c>knowledge.catalog.write</c> (<c>auth.missing_scope</c>).</response>
    /// <response code="404">The collection does not exist (<c>knowledge.collection.not_found</c>).</response>
    /// <response code="409">
    /// The collection was changed by another request between reading and saving (<c>persistence.concurrency_conflict</c>);
    /// reload it and retry.
    /// </response>
    /// <response code="422">The collection is archived (<c>knowledge.collection.archived</c>).</response>
    [HttpPut("v1/knowledge/collections/{collectionId:guid}/categories")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status404NotFound, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status409Conflict, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status422UnprocessableEntity, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> SetCategories(System.Guid collectionId, [FromBody] SetCategoriesRequest body, CancellationToken cancellationToken) =>
        this.ToActionResult(await knowledge.CollectionsSetCategoriesAsync(collectionId, body, cancellationToken));

    /// <summary>Publishes a collection, making it visible to readers.</summary>
    /// <remarks>
    /// Required scope: <c>knowledge.catalog.write</c> (editor). The collection must contain at least one material. The operation is
    /// idempotent: publishing an already published collection succeeds without changes (the original publication date is kept).
    /// No integration event is published for collections.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="collectionId">Identifier of the collection.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="204">The collection is published.</response>
    /// <response code="400">Empty identifier (<c>validation.failed</c>).</response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">The token lacks the scope <c>knowledge.catalog.write</c> (<c>auth.missing_scope</c>).</response>
    /// <response code="404">The collection does not exist (<c>knowledge.collection.not_found</c>).</response>
    /// <response code="409">
    /// The collection was changed by another request between reading and saving (<c>persistence.concurrency_conflict</c>);
    /// reload it and retry.
    /// </response>
    /// <response code="422">
    /// The collection is archived or has no materials (<c>knowledge.collection.archived</c>, <c>knowledge.collection.items_required</c>).
    /// </response>
    [HttpPost("v1/knowledge/collections/{collectionId:guid}/publish")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status404NotFound, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status409Conflict, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status422UnprocessableEntity, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> Publish(System.Guid collectionId, CancellationToken cancellationToken) =>
        this.ToActionResult(await knowledge.CollectionsPublishAsync(collectionId, cancellationToken));

    /// <summary>Archives a collection: it is hidden from readers and removed from users' favorites.</summary>
    /// <remarks>
    /// Required scope: <c>knowledge.catalog.write</c> (editor). Archiving is irreversible (an archived collection can be neither changed
    /// nor published again) and publishes the integration event <c>CollectionArchivedV1</c>. Favorites pointing to the collection are
    /// removed asynchronously, shortly after the response; until then they are already hidden from the favorites list. Materials in the
    /// collection are not affected. The operation is idempotent: archiving an already archived collection succeeds without changes.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="collectionId">Identifier of the collection.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="204">The collection is archived.</response>
    /// <response code="400">Empty identifier (<c>validation.failed</c>).</response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">The token lacks the scope <c>knowledge.catalog.write</c> (<c>auth.missing_scope</c>).</response>
    /// <response code="404">The collection does not exist (<c>knowledge.collection.not_found</c>).</response>
    /// <response code="409">
    /// The collection was changed by another request between reading and saving (<c>persistence.concurrency_conflict</c>);
    /// reload it and retry.
    /// </response>
    [HttpPost("v1/knowledge/collections/{collectionId:guid}/archive")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status404NotFound, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status409Conflict, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> Archive(System.Guid collectionId, CancellationToken cancellationToken) =>
        this.ToActionResult(await knowledge.CollectionsArchiveAsync(collectionId, cancellationToken));
}
