using SuperApp.Framework.Infrastructure.Api;
using Example.Bff.Clients.Knowledge;
using Microsoft.AspNetCore.Mvc;
using System.Net.Mime;

namespace Example.Bff.Controllers.Knowledge;

/// <summary>
/// Public API of the Example experience for <c>Library</c> of the Knowledge service: the module calls these endpoints, and the
/// BFF passes each call on to the Knowledge service with the user's token (ADR-0038, ADR-0039, ADR-0040).
/// </summary>
/// <remarks>
/// Pass-through endpoints: request and response bodies are the service's contract types generated by Refitter, and the service's
/// answer, including its error status and <c>code</c>, is relayed unchanged (<c>DownstreamResponseExtensions</c>). Authorization
/// (scopes, resource rules) is decided by the Knowledge service. When the service cannot be reached the BFF answers
/// <c>503 downstream.unavailable</c> or <c>504 downstream.timeout</c>.
/// </remarks>
/// <param name="knowledge">Client of the Knowledge service, generated from its committed OpenAPI contract.</param>
[ApiController]
[Tags("Knowledge – Library")]
public sealed class KnowledgeLibraryController(IKnowledgeApi knowledge) : ControllerBase
{
    /// <summary>Returns a page of the caller's favorites, most recently added first.</summary>
    /// <remarks>
    /// Required scope: <c>knowledge.library.read</c>. Only items that are still published are returned: favorites pointing to a material
    /// or collection that has since been archived are hidden (and are removed in the background shortly after archiving). The total
    /// count also counts only visible items.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="page">Page number starting at 1; values lower than 1 are treated as 1.</param>
    /// <param name="pageSize">Page size, 20 by default, clamped to the range 1–100.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="200">The requested page (possibly empty).</response>
    /// <response code="400">
    /// A query parameter has an invalid format (<c>page</c> or <c>pageSize</c> is not an integer); rejected by the framework with a validation problem with <c>code</c> <c>request.malformed</c> (ADR-0044).
    /// </response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">
    /// The token lacks the scope <c>knowledge.library.read</c> (<c>auth.missing_scope</c>) or has no user identifier
    /// (<c>auth.unauthenticated</c>).
    /// </response>
    [HttpGet("v1/knowledge/me/favorites")]
    [ProducesResponseType<PagedResultOfFavoriteDto>(StatusCodes.Status200OK, MediaTypeNames.Application.Json)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> Favorites([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken) =>
        this.ToActionResult(await knowledge.LibraryFavoritesAsync(page, pageSize, cancellationToken));

    /// <summary>Adds a published material or collection to the caller's favorites.</summary>
    /// <remarks>
    /// Required scope: <c>knowledge.library.write</c>. Only published items can be added. The operation is idempotent: adding an item
    /// that is already a favorite succeeds without changes and keeps the original date added.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="itemType">Kind of the item: <c>Material</c> or <c>Collection</c>.</param>
    /// <param name="itemId">Identifier of the material or collection.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="204">The item is in the favorites.</response>
    /// <response code="400">Invalid item type or an empty identifier (<c>validation.failed</c>).</response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">
    /// The token lacks the scope <c>knowledge.library.write</c> (<c>auth.missing_scope</c>) or has no user identifier
    /// (<c>auth.unauthenticated</c>).
    /// </response>
    /// <response code="404">The item does not exist or is not published (<c>knowledge.library.item_not_available</c>).</response>
    /// <response code="409">
    /// Only when two requests add the same item at the same moment: the other request stored it first
    /// (<c>knowledge.library.favorite_added_concurrently</c>). The item is in the favorites; retrying returns 204.
    /// </response>
    [HttpPut("v1/knowledge/me/favorites/{itemType}/{itemId:guid}")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status404NotFound, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status409Conflict, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> AddFavorite(FavoriteItemType itemType, System.Guid itemId, CancellationToken cancellationToken) =>
        this.ToActionResult(await knowledge.LibraryAddFavoriteAsync(itemType, itemId, cancellationToken));

    /// <summary>Removes a material or collection from the caller's favorites.</summary>
    /// <remarks>
    /// Required scope: <c>knowledge.library.write</c>. Works for items in any status, including archived ones. The operation is
    /// idempotent: removing an item that is not a favorite succeeds.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="itemType">Kind of the item: <c>Material</c> or <c>Collection</c>.</param>
    /// <param name="itemId">Identifier of the material or collection.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="204">The item is not in the favorites (any more).</response>
    /// <response code="400">Invalid item type or an empty identifier (<c>validation.failed</c>).</response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">
    /// The token lacks the scope <c>knowledge.library.write</c> (<c>auth.missing_scope</c>) or has no user identifier
    /// (<c>auth.unauthenticated</c>).
    /// </response>
    [HttpDelete("v1/knowledge/me/favorites/{itemType}/{itemId:guid}")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> RemoveFavorite(FavoriteItemType itemType, System.Guid itemId, CancellationToken cancellationToken) =>
        this.ToActionResult(await knowledge.LibraryRemoveFavoriteAsync(itemType, itemId, cancellationToken));

    /// <summary>Returns a page of materials the caller marked as completed, most recently marked first.</summary>
    /// <remarks>
    /// Required scope: <c>knowledge.library.read</c>. Like favorites, only materials that are currently published are listed and counted;
    /// a mark on a material that was archived later is kept but not shown.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="page">Page number starting at 1; values lower than 1 are treated as 1.</param>
    /// <param name="pageSize">Page size, 20 by default, clamped to the range 1–100.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="200">The requested page (possibly empty).</response>
    /// <response code="400">
    /// A query parameter has an invalid format (<c>page</c> or <c>pageSize</c> is not an integer); rejected by the framework with a validation problem with <c>code</c> <c>request.malformed</c> (ADR-0044).
    /// </response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">
    /// The token lacks the scope <c>knowledge.library.read</c> (<c>auth.missing_scope</c>) or has no user identifier
    /// (<c>auth.unauthenticated</c>).
    /// </response>
    [HttpGet("v1/knowledge/me/completions")]
    [ProducesResponseType<PagedResultOfCompletedMaterialDto>(StatusCodes.Status200OK, MediaTypeNames.Application.Json)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> Completions([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken) =>
        this.ToActionResult(await knowledge.LibraryCompletionsAsync(page, pageSize, cancellationToken));

    /// <summary>Marks a published material as completed by the caller.</summary>
    /// <remarks>
    /// Required scope: <c>knowledge.library.write</c>. Only published materials can be marked. The operation is idempotent: marking
    /// an already completed material succeeds and keeps the original date marked.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="materialId">Identifier of the material.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="204">The material is marked as completed.</response>
    /// <response code="400">Empty identifier (<c>validation.failed</c>).</response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">
    /// The token lacks the scope <c>knowledge.library.write</c> (<c>auth.missing_scope</c>) or has no user identifier
    /// (<c>auth.unauthenticated</c>).
    /// </response>
    /// <response code="404">The material does not exist or is not published (<c>knowledge.library.item_not_available</c>).</response>
    /// <response code="409">
    /// Only when two requests mark the same material at the same moment: the other request stored the mark first
    /// (<c>knowledge.library.completion_recorded_concurrently</c>). The material is marked; retrying returns 204.
    /// </response>
    [HttpPut("v1/knowledge/me/completions/{materialId:guid}")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status404NotFound, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status409Conflict, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> MarkCompleted(System.Guid materialId, CancellationToken cancellationToken) =>
        this.ToActionResult(await knowledge.LibraryMarkCompletedAsync(materialId, cancellationToken));

    /// <summary>Removes the caller's completion mark from a material.</summary>
    /// <remarks>
    /// Required scope: <c>knowledge.library.write</c>. Works for materials in any status. The operation is idempotent: removing a mark
    /// that does not exist succeeds.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="materialId">Identifier of the material.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="204">The material is not marked as completed (any more).</response>
    /// <response code="400">Empty identifier (<c>validation.failed</c>).</response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">
    /// The token lacks the scope <c>knowledge.library.write</c> (<c>auth.missing_scope</c>) or has no user identifier
    /// (<c>auth.unauthenticated</c>).
    /// </response>
    [HttpDelete("v1/knowledge/me/completions/{materialId:guid}")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> UnmarkCompleted(System.Guid materialId, CancellationToken cancellationToken) =>
        this.ToActionResult(await knowledge.LibraryUnmarkCompletedAsync(materialId, cancellationToken));
}
