using SuperApp.Framework.Infrastructure.Api;
using Example.Bff.Clients.Knowledge;
using Microsoft.AspNetCore.Mvc;
using System.Net.Mime;

namespace Example.Bff.Controllers.Knowledge;

/// <summary>
/// Public API of the Example experience for <c>Categories</c> of the Knowledge service: the module calls these endpoints, and the
/// BFF passes each call on to the Knowledge service with the user's token (ADR-0038, ADR-0039, ADR-0040).
/// </summary>
/// <remarks>
/// Pass-through endpoints: request and response bodies are the service's contract types generated by Refitter, and the service's
/// answer, including its error status and <c>code</c>, is relayed unchanged (<c>DownstreamResponseExtensions</c>). Authorization
/// (scopes, resource rules) is decided by the Knowledge service. When the service cannot be reached the BFF answers
/// <c>503 downstream.unavailable</c> or <c>504 downstream.timeout</c>.
/// </remarks>
/// <param name="knowledge">Client of the Knowledge service, generated from its committed OpenAPI contract.</param>
[ApiController]
[Tags("Knowledge – Categories")]
public sealed class KnowledgeCategoriesController(IKnowledgeApi knowledge) : ControllerBase
{
    /// <summary>Returns all categories of the catalog, ordered by name.</summary>
    /// <remarks>
    /// Required scope: <c>knowledge.catalog.read</c>. The list is not paged (the catalog is expected to have few categories) and is
    /// served from a cache that is refreshed immediately after a category is created or renamed.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="200">The list of categories (possibly empty).</response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">The token lacks the scope <c>knowledge.catalog.read</c> (<c>auth.missing_scope</c>).</response>
    [HttpGet("v1/knowledge/categories")]
    [ProducesResponseType<ICollection<CategoryDto>>(StatusCodes.Status200OK, MediaTypeNames.Application.Json)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> List(CancellationToken cancellationToken) =>
        this.ToActionResult(await knowledge.CategoriesListAsync(cancellationToken));

    /// <summary>Creates a new category.</summary>
    /// <remarks>
    /// Required scope: <c>knowledge.catalog.write</c> (editor). Name: required, at most 100 characters (leading and trailing whitespace is
    /// trimmed). Slug: required, at most 100 characters, only lowercase letters, digits and single hyphens between them
    /// (e.g. <c>healthy-sleep</c>), unique across all categories. The slug cannot be changed later.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="body">Name and slug of the new category.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="201">The category was created; the body contains its identifier.</response>
    /// <response code="400">
    /// Invalid name or slug (<c>validation.failed</c>, <c>knowledge.category.invalid_name</c>, <c>knowledge.category.invalid_slug</c>).
    /// </response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">The token lacks the scope <c>knowledge.catalog.write</c> (<c>auth.missing_scope</c>).</response>
    /// <response code="409">
    /// A category with this slug already exists (<c>knowledge.category.slug_taken</c>), also when another request created it at the same moment.
    /// </response>
    [HttpPost("v1/knowledge/categories")]
    [ProducesResponseType<CreatedResponse>(StatusCodes.Status201Created, MediaTypeNames.Application.Json)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status409Conflict, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> Create([FromBody] CreateCategory body, CancellationToken cancellationToken) =>
        this.ToActionResult(await knowledge.CategoriesCreateAsync(body, cancellationToken));

    /// <summary>Renames a category; its slug stays unchanged.</summary>
    /// <remarks>
    /// Required scope: <c>knowledge.catalog.write</c> (editor). Name: required, at most 100 characters (trimmed).
    /// Renaming to the current name succeeds.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation of the HTTP request.</param>
    /// <param name="categoryId">Identifier of the category.</param>
    /// <param name="body">The new name of the category.</param>
    /// <returns>The service's answer, relayed unchanged.</returns>
    /// <response code="204">The category was renamed.</response>
    /// <response code="400">Invalid name or an empty identifier (<c>validation.failed</c>, <c>knowledge.category.invalid_name</c>).</response>
    /// <response code="401">Missing, expired or invalid access token.</response>
    /// <response code="403">The token lacks the scope <c>knowledge.catalog.write</c> (<c>auth.missing_scope</c>).</response>
    /// <response code="404">The category does not exist (<c>knowledge.category.not_found</c>).</response>
    /// <response code="409">
    /// The category was changed by another request between reading and saving (<c>persistence.concurrency_conflict</c>);
    /// reload it and retry.
    /// </response>
    [HttpPut("v1/knowledge/categories/{categoryId:guid}/name")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ValidationProblemDetails>(StatusCodes.Status400BadRequest, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status403Forbidden, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status404NotFound, MediaTypeNames.Application.ProblemJson)]
    [ProducesResponseType<Microsoft.AspNetCore.Mvc.ProblemDetails>(StatusCodes.Status409Conflict, MediaTypeNames.Application.ProblemJson)]
    public async Task<IActionResult> Rename(System.Guid categoryId, [FromBody] RenameCategoryRequest body, CancellationToken cancellationToken) =>
        this.ToActionResult(await knowledge.CategoriesRenameAsync(categoryId, body, cancellationToken));
}
