using Microsoft.Extensions.DependencyInjection;

namespace SuperApp.Framework.Infrastructure.Http.ClientCredentials;

/// <summary>
/// Adds OAuth client credentials tokens to HTTP clients used for synchronous service-to-service calls (ADR-0011, ADR-0014).
/// </summary>
/// <remarks>
/// <para>
/// Synchronous calls between services are the exception (events are the default) and always go through an anti-corruption layer in the calling
/// service's Infrastructure project. The client is a Refit interface generated by Refitter from the provider's committed OpenAPI contract.
/// </para>
/// <para>Configuration of a client named <c>knowledge-client</c>, with the secret supplied from Vault:</para>
/// <code>
/// "ClientCredentials": {
///   "knowledge-client": {
///     "TokenEndpoint": "https://sso.example.com/realms/superapp/protocol/openid-connect/token",
///     "ClientId": "sleepdiary-client",
///     "Scope": "knowledge.system.read"
///   }
/// }
/// </code>
/// </remarks>
/// <example>
/// <code>
/// // A system call (no user, ADR-0040, ADR-0042); calls in the user's context use AddUserTokenForwarding instead.
/// services.AddDownstreamApi&lt;IKnowledgeApi&gt;(configuration, "Knowledge")
///     .AddClientCredentialsToken("knowledge-client");
/// </code>
/// </example>
public static class ClientCredentialsHttpClientBuilderExtensions
{
    /// <summary>
    /// Makes every request of this HTTP client carry <c>Authorization: Bearer</c> with a client credentials token of <paramref name="clientName"/>,
    /// obtained from the CIAM and cached until shortly before it expires.
    /// </summary>
    /// <param name="builder">The HTTP client builder, e.g. returned by <c>AddRefitClient&lt;T&gt;()</c>.</param>
    /// <param name="clientName">
    /// Name of the configuration section <c>ClientCredentials:{clientName}</c> holding the <see cref="ClientCredentialsOptions"/>; also the cache key of the token.
    /// </param>
    /// <remarks>
    /// The options are validated when the host starts: a missing token endpoint, client ID or secret stops the host with a clear message
    /// instead of failing on the first call.
    /// </remarks>
    /// <returns>The same <paramref name="builder"/>, for chaining (add the resilience handler after this call).</returns>
    public static IHttpClientBuilder AddClientCredentialsToken(this IHttpClientBuilder builder, string clientName)
    {
        builder.Services.AddHttpClient(ClientCredentialsTokenProvider.TokenHttpClientName);
        builder.Services.AddSingleton<ClientCredentialsTokenProvider>();
        builder.Services.AddOptions<ClientCredentialsOptions>(clientName)
            .BindConfiguration($"ClientCredentials:{clientName}")
            .Validate(
                options => options.TokenEndpoint is { IsAbsoluteUri: true }
                    && !string.IsNullOrWhiteSpace(options.ClientId)
                    && !string.IsNullOrWhiteSpace(options.ClientSecret),
                $"ClientCredentials:{clientName} wymaga TokenEndpoint (absolutny URI), ClientId i ClientSecret.")
            .ValidateOnStart();
        return builder.AddHttpMessageHandler(provider =>
            new ClientCredentialsTokenHandler(provider.GetRequiredService<ClientCredentialsTokenProvider>(), clientName));
    }
}
