namespace SuperApp.Cli.Scaffolding;

/// <summary>One step of a <see cref="ScaffoldPlan"/>: a description for the plan and the action that performs it.</summary>
/// <remarks>
/// The action reads the current content when it runs (not when the plan is built), so a step may depend on files created by an earlier
/// step, e.g. the solution step lists the projects generated by <c>dotnet new</c>. Every action must be idempotent: when its change is
/// already there it returns <see cref="StepStatus.Unchanged"/>.
/// </remarks>
/// <param name="Target">File, directory or command the step works on, relative to the repository root.</param>
/// <param name="Description">What the step does, shown in the plan.</param>
/// <param name="Apply">Performs the step and reports what changed.</param>
internal sealed record ScaffoldStep(string Target, string Description, Func<ScaffoldContext, IEnumerable<StepResult>> Apply);
