using Knowledge.Domain.Categories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Knowledge.Infrastructure.Persistence.Write.Configurations;

// EF configuration lives only in IEntityTypeConfiguration<T> classes; IDs and single-value objects are mapped by a convention (ADR-0023, ADR-0024).

/// <summary>Maps the <see cref="Category"/> aggregate onto the table <c>knowledge.Categories</c>.</summary>
/// <remarks>
/// <list type="bullet">
///   <item><description>Primary key <c>Id</c>; the value is generated by the domain (<c>CategoryId.New()</c>), never by the database.</description></item>
///   <item><description><c>Name</c> and <c>Slug</c> are limited to <see cref="Category.MaxNameLength"/> and <see cref="Category.MaxSlugLength"/> characters.</description></item>
///   <item><description>A unique index on <c>Slug</c> backs the uniqueness check of the create handler against concurrent inserts.</description></item>
///   <item><description>The shadow property <c>Version</c> (<c>rowversion</c>) is an optimistic concurrency token.</description></item>
///   <item><description><c>DomainEvents</c> is not persisted; events are dispatched on save (ADR-0027).</description></item>
/// </list>
/// Write-side configurations are the source of truth for the schema: migrations of <see cref="KnowledgeWriteDbContext"/> are generated
/// from them.
/// </remarks>
internal sealed class CategoryConfiguration : IEntityTypeConfiguration<Category>
{
    /// <inheritdoc />
    public void Configure(EntityTypeBuilder<Category> builder)
    {
        builder.ToTable("Categories");
        builder.HasKey(category => category.Id);
        builder.Property(category => category.Id).ValueGeneratedNever();
        builder.Property(category => category.Name).HasMaxLength(Category.MaxNameLength);
        builder.Property(category => category.Slug).HasMaxLength(Category.MaxSlugLength);
        builder.HasIndex(category => category.Slug).IsUnique();
        builder.Property<byte[]>("Version").IsRowVersion();
        builder.Ignore(category => category.DomainEvents);
    }
}
