using Knowledge.Domain.Collections;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Knowledge.Infrastructure.Persistence.Write.Configurations;

/// <summary>Maps the <see cref="Collection"/> aggregate onto <c>knowledge.Collections</c> and its two owned tables.</summary>
/// <remarks>
/// <list type="bullet">
///   <item><description>
///   <c>Collections</c>: primary key <c>Id</c> (generated by the domain); <c>Status</c> stored as the enum name (<c>nvarchar(20)</c>);
///   <c>Title</c> and <c>Description</c> limited to <see cref="Collection.MaxTitleLength"/> and <see cref="Collection.MaxDescriptionLength"/>;
///   shadow <c>Version</c> (<c>rowversion</c>) as concurrency token; index (<c>Status</c>, <c>PublishedAt</c>) for the reader list.
///   </description></item>
///   <item><description>
///   <c>CollectionItems</c> (<c>OwnsMany</c> of <see cref="CollectionItem"/>): key (<c>CollectionId</c>, <c>Position</c>), check
///   <c>CK_CollectionItems_Position</c> (position &gt;= 0), index on <c>MaterialId</c>. <c>Position</c> is set by the aggregate, never
///   generated by the database. Items are owned, so they are loaded and replaced
///   together with the collection.
///   </description></item>
///   <item><description>
///   <c>CollectionCategories</c> (<c>OwnsMany</c> of <see cref="CollectionCategory"/>): key (<c>CollectionId</c>, <c>CategoryId</c>),
///   index on <c>CategoryId</c> for filtering by category.
///   </description></item>
/// </list>
/// References to materials and categories are identifiers only, without foreign keys: they point to other aggregates.
/// </remarks>
internal sealed class CollectionConfiguration : IEntityTypeConfiguration<Collection>
{
    /// <inheritdoc />
    public void Configure(EntityTypeBuilder<Collection> builder)
    {
        builder.ToTable("Collections");
        builder.HasKey(collection => collection.Id);
        builder.Property(collection => collection.Id).ValueGeneratedNever();
        builder.Property(collection => collection.Status).HasConversion<string>().HasMaxLength(20);
        builder.Property(collection => collection.Title).HasMaxLength(Collection.MaxTitleLength);
        builder.Property(collection => collection.Description).HasMaxLength(Collection.MaxDescriptionLength);
        builder.Property<byte[]>("Version").IsRowVersion();
        builder.HasIndex(collection => new { collection.Status, collection.PublishedAt });
        builder.Ignore(collection => collection.DomainEvents);

        builder.OwnsMany(collection => collection.Items, items =>
        {
            items.ToTable("CollectionItems", table => table.HasCheckConstraint("CK_CollectionItems_Position", "[Position] >= 0"));
            items.WithOwner().HasForeignKey("CollectionId");
            items.HasKey("CollectionId", nameof(CollectionItem.Position));

            // The position is assigned by the aggregate (0..n-1). Without this, EF Core treats the int part of an owned collection key as
            // store generated (an IDENTITY column): a new item at position 0 got a temporary key and every other new item was taken for an
            // existing row and updated, which failed with a concurrency exception.
            items.Property(item => item.Position).ValueGeneratedNever();
            items.HasIndex(item => item.MaterialId);
        });

        builder.OwnsMany(collection => collection.Categories, categories =>
        {
            categories.ToTable("CollectionCategories");
            categories.WithOwner().HasForeignKey("CollectionId");
            categories.HasKey("CollectionId", nameof(CollectionCategory.CategoryId));
            categories.HasIndex(category => category.CategoryId);
        });
    }
}
