using Knowledge.Domain.Materials;
using Knowledge.Domain.Common;
using Knowledge.Domain.Materials.Content;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Knowledge.Infrastructure.Persistence.Write.Configurations;

/// <summary>
/// Maps <see cref="ContentBlock"/> (a node of the block content of a material) onto <c>knowledge.ContentBlocks</c> and its formatted
/// text spans onto <c>knowledge.ContentTextSpans</c> (ADR-0028).
/// </summary>
/// <remarks>
/// <para>
/// One table holds all block types; type-specific columns are nullable and the rules the domain enforces are repeated as <c>CHECK</c>
/// constraints, so that invalid content cannot be written even by bypassing the domain (e.g. a manual SQL fix). Every condition checks
/// <c>IS NOT NULL</c> explicitly, because a comparison with <c>NULL</c> evaluates to unknown and a <c>CHECK</c> constraint accepts unknown.
/// </para>
/// <list type="bullet">
///   <item><description>Primary key <c>Id</c> (generated by the domain); <c>Type</c> stored as the <see cref="BlockType"/> name (<c>nvarchar(30)</c>).</description></item>
///   <item><description>Shadow foreign key <c>MaterialId</c> to the owning material (configured with cascade delete in <see cref="MaterialConfiguration"/>).</description></item>
///   <item><description>
///   Self-reference <c>ParentBlockId</c> without cascade (<c>NoAction</c>), because SQL Server does not allow a second cascade path;
///   child rows are deleted by EF together with the material's blocks.
///   </description></item>
///   <item><description>Index (<c>MaterialId</c>, <c>ParentBlockId</c>, <c>Position</c>) for loading the tree of one material.</description></item>
///   <item><description>
///   <c>ContentTextSpans</c> (<c>OwnsMany</c> of <see cref="TextSpan"/>): key (<c>BlockId</c>, <c>Position</c>) with the position set by the
///   domain (not generated by the database), <c>Marks</c> stored as the
///   integer value of the flags enum, links restricted to <c>https://</c> and <c>mailto:</c> by <c>CK_ContentTextSpans_Link</c>.
///   </description></item>
/// </list>
/// <para>
/// Adding a block type means a new enum value, possibly new columns and <c>CHECK</c> constraints here, and a new migration.
/// </para>
/// </remarks>
internal sealed class ContentBlockConfiguration : IEntityTypeConfiguration<ContentBlock>
{
    // Block types that may only appear as children of a container block; CK_ContentBlocks_ChildHasParent requires a parent for them.
    private const string ChildTypes = "'ListItem','ChecklistItem','TakeawayItem','TableRow','TableCell','TranscriptSegment'";

    /// <inheritdoc />
    public void Configure(EntityTypeBuilder<ContentBlock> builder)
    {
        builder.ToTable("ContentBlocks", table =>
        {
            table.HasCheckConstraint("CK_ContentBlocks_Position", "[Position] >= 0");
            table.HasCheckConstraint("CK_ContentBlocks_ChildHasParent", $"[Type] NOT IN ({ChildTypes}) OR [ParentBlockId] IS NOT NULL");
            table.HasCheckConstraint("CK_ContentBlocks_Heading", "[Type] <> 'Heading' OR ([Level] IS NOT NULL AND [Level] BETWEEN 1 AND 4 AND [PlainText] IS NOT NULL)");
            table.HasCheckConstraint("CK_ContentBlocks_Code", "[Type] <> 'Code' OR [PlainText] IS NOT NULL");
            table.HasCheckConstraint("CK_ContentBlocks_List", "[Type] <> 'List' OR ([Variant] IS NOT NULL AND [Variant] IN ('Ordered','Unordered'))");
            table.HasCheckConstraint("CK_ContentBlocks_Callout", "[Type] <> 'Callout' OR ([Variant] IS NOT NULL AND [Variant] IN ('Info','Tip','Warning','Important'))");
            table.HasCheckConstraint("CK_ContentBlocks_Title", "[Type] NOT IN ('Toggle','LinkCard') OR [Title] IS NOT NULL");
            table.HasCheckConstraint("CK_ContentBlocks_Image", "[Type] <> 'Image' OR ([Url] IS NOT NULL AND [AltText] IS NOT NULL)");
            table.HasCheckConstraint("CK_ContentBlocks_MediaUrl", "[Type] NOT IN ('Video','Audio','Embed','LinkCard') OR [Url] IS NOT NULL");
            table.HasCheckConstraint("CK_ContentBlocks_UrlHttps", "[Url] IS NULL OR [Url] LIKE 'https://%'");
            table.HasCheckConstraint("CK_ContentBlocks_ChecklistItem", "[Type] <> 'ChecklistItem' OR [IsChecked] IS NOT NULL");
            table.HasCheckConstraint("CK_ContentBlocks_AtSeconds", "[Type] NOT IN ('Timestamp','TranscriptSegment') OR ([AtSeconds] IS NOT NULL AND [AtSeconds] >= 0)");
            table.HasCheckConstraint("CK_ContentBlocks_Duration", "[DurationSeconds] IS NULL OR [DurationSeconds] >= 0");
        });

        builder.HasKey(block => block.Id);
        builder.Property(block => block.Id).ValueGeneratedNever();
        builder.Property(block => block.Type).HasConversion<string>().HasMaxLength(30);
        builder.Property(block => block.Variant).HasMaxLength(20);
        builder.Property(block => block.Title).HasMaxLength(200);
        builder.Property(block => block.PlainText).HasMaxLength(ContentBuilder.MaxCodeLength);
        builder.Property(block => block.Url).HasMaxLength(WebUrl.MaxLength);
        builder.Property(block => block.AltText).HasMaxLength(300);
        builder.Property(block => block.Caption).HasMaxLength(300);
        builder.Property(block => block.Credit).HasMaxLength(200);
        builder.Property(block => block.Language).HasMaxLength(30);
        builder.Property(block => block.Speaker).HasMaxLength(100);
        builder.Property(block => block.Author).HasMaxLength(200);
        builder.Property(block => block.Source).HasMaxLength(200);
        builder.Property(block => block.Description).HasMaxLength(500);
        builder.Property<MaterialId>("MaterialId");
        builder.HasIndex("MaterialId", nameof(ContentBlock.ParentBlockId), nameof(ContentBlock.Position));

        builder.HasOne<ContentBlock>()
            .WithMany()
            .HasForeignKey(block => block.ParentBlockId)
            .OnDelete(DeleteBehavior.NoAction);

        builder.OwnsMany(block => block.Spans, spans =>
        {
            spans.ToTable("ContentTextSpans", table => table.HasCheckConstraint(
                "CK_ContentTextSpans_Link", "[LinkHref] IS NULL OR [LinkHref] LIKE 'https://%' OR [LinkHref] LIKE 'mailto:%'"));
            spans.WithOwner().HasForeignKey("BlockId");
            spans.HasKey("BlockId", nameof(TextSpan.Position));

            // The position is assigned by the content builder (0..n-1). Without this, EF Core treats the int part of an owned collection
            // key as store generated (an IDENTITY column), and a block with more than one span failed to save.
            spans.Property(span => span.Position).ValueGeneratedNever();
            spans.Property(span => span.Text).HasMaxLength(ContentBuilder.MaxSpanLength);
            spans.Property(span => span.LinkHref).HasMaxLength(WebUrl.MaxLength);
        });
    }
}
