using Knowledge.Domain.Library.Favorites;
using Knowledge.Domain.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Knowledge.Infrastructure.Persistence.Write.Configurations;

/// <summary>Maps the <see cref="Favorite"/> aggregate onto the table <c>knowledge.Favorites</c>.</summary>
/// <remarks>
/// <list type="bullet">
///   <item><description>Primary key <c>Id</c> (generated by the domain).</description></item>
///   <item><description><c>UserId</c> (the <c>sub</c> claim) limited to <see cref="UserId.MaxLength"/> characters; <c>ItemType</c> stored as the enum name (<c>nvarchar(20)</c>).</description></item>
///   <item><description>
///   Unique index (<c>UserId</c>, <c>ItemType</c>, <c>ItemId</c>): a user can have an item among favorites only once, even when two
///   requests add it concurrently (the second insert fails).
///   </description></item>
///   <item><description>Index (<c>ItemType</c>, <c>ItemId</c>) for removing all favorites of an archived item.</description></item>
///   <item><description><c>ItemId</c> has no foreign key, because it points either to a material or to a collection.</description></item>
/// </list>
/// </remarks>
internal sealed class FavoriteConfiguration : IEntityTypeConfiguration<Favorite>
{
    /// <inheritdoc />
    public void Configure(EntityTypeBuilder<Favorite> builder)
    {
        builder.ToTable("Favorites");
        builder.HasKey(favorite => favorite.Id);
        builder.Property(favorite => favorite.Id).ValueGeneratedNever();
        builder.Property(favorite => favorite.UserId).HasMaxLength(UserId.MaxLength);
        builder.Property(favorite => favorite.ItemType).HasConversion<string>().HasMaxLength(20);
        builder.HasIndex(favorite => new { favorite.UserId, favorite.ItemType, favorite.ItemId }).IsUnique();
        builder.HasIndex(favorite => new { favorite.ItemType, favorite.ItemId });
        builder.Ignore(favorite => favorite.DomainEvents);
    }
}
