using Knowledge.Domain.Common;
using Knowledge.Domain.Materials;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Knowledge.Infrastructure.Persistence.Write.Configurations;

/// <summary>Maps the <see cref="Material"/> aggregate onto <c>knowledge.Materials</c>, its categories and its content blocks.</summary>
/// <remarks>
/// <list type="bullet">
///   <item><description>
///   <c>Materials</c>: primary key <c>Id</c> (generated by the domain); <c>Type</c> and <c>Status</c> stored as enum names
///   (<c>nvarchar(20)</c>); <c>Title</c>, <c>Description</c> and <c>MainMediaUrl</c> limited to <see cref="Material.MaxTitleLength"/>,
///   <see cref="Material.MaxDescriptionLength"/> and <see cref="WebUrl.MaxLength"/>; checks <c>CK_Materials_MainMediaUrl</c> (only
///   <c>https://</c>) and <c>CK_Materials_ReadingTime</c> (not negative); shadow <c>Version</c> (<c>rowversion</c>) as concurrency token;
///   index (<c>Status</c>, <c>PublishedAt</c>) for the reader list.
///   </description></item>
///   <item><description>
///   <c>MaterialCategories</c> (<c>OwnsMany</c> of <see cref="MaterialCategory"/>): key (<c>MaterialId</c>, <c>CategoryId</c>), index on
///   <c>CategoryId</c>; no foreign key to categories (another aggregate).
///   </description></item>
///   <item><description>
///   <c>ContentBlocks</c>: a one-to-many relationship through the shadow foreign key <c>MaterialId</c> with cascade delete; the blocks are
///   entities of the aggregate configured in <see cref="ContentBlockConfiguration"/>.
///   </description></item>
/// </list>
/// </remarks>
internal sealed class MaterialConfiguration : IEntityTypeConfiguration<Material>
{
    /// <inheritdoc />
    public void Configure(EntityTypeBuilder<Material> builder)
    {
        builder.ToTable("Materials", table =>
        {
            table.HasCheckConstraint("CK_Materials_MainMediaUrl", "[MainMediaUrl] IS NULL OR [MainMediaUrl] LIKE 'https://%'");
            table.HasCheckConstraint("CK_Materials_ReadingTime", "[ReadingTimeMinutes] >= 0");
        });
        builder.HasKey(material => material.Id);
        builder.Property(material => material.Id).ValueGeneratedNever();
        builder.Property(material => material.Type).HasConversion<string>().HasMaxLength(20);
        builder.Property(material => material.Status).HasConversion<string>().HasMaxLength(20);
        builder.Property(material => material.Title).HasMaxLength(Material.MaxTitleLength);
        builder.Property(material => material.Description).HasMaxLength(Material.MaxDescriptionLength);
        builder.Property(material => material.MainMediaUrl).HasMaxLength(WebUrl.MaxLength);
        builder.Property<byte[]>("Version").IsRowVersion();
        builder.HasIndex(material => new { material.Status, material.PublishedAt });
        builder.Ignore(material => material.DomainEvents);

        builder.OwnsMany(material => material.Categories, categories =>
        {
            categories.ToTable("MaterialCategories");
            categories.WithOwner().HasForeignKey("MaterialId");
            categories.HasKey("MaterialId", nameof(MaterialCategory.CategoryId));
            categories.HasIndex(category => category.CategoryId);
        });

        builder.HasMany(material => material.Blocks)
            .WithOne()
            .HasForeignKey("MaterialId")
            .OnDelete(DeleteBehavior.Cascade);
    }
}
