using Knowledge.Domain.Library.Completions;
using Knowledge.Domain.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Knowledge.Infrastructure.Persistence.Write.Configurations;

/// <summary>Maps the <see cref="MaterialCompletion"/> aggregate onto the table <c>knowledge.MaterialCompletions</c>.</summary>
/// <remarks>
/// Primary key <c>Id</c> (generated by the domain); <c>UserId</c> limited to <see cref="UserId.MaxLength"/> characters; unique index
/// (<c>UserId</c>, <c>MaterialId</c>) so that a user can mark a material only once, even under concurrent requests. <c>MaterialId</c> has no
/// foreign key (another aggregate).
/// </remarks>
internal sealed class MaterialCompletionConfiguration : IEntityTypeConfiguration<MaterialCompletion>
{
    /// <inheritdoc />
    public void Configure(EntityTypeBuilder<MaterialCompletion> builder)
    {
        builder.ToTable("MaterialCompletions");
        builder.HasKey(completion => completion.Id);
        builder.Property(completion => completion.Id).ValueGeneratedNever();
        builder.Property(completion => completion.UserId).HasMaxLength(UserId.MaxLength);
        builder.HasIndex(completion => new { completion.UserId, completion.MaterialId }).IsUnique();
        builder.Ignore(completion => completion.DomainEvents);
    }
}
