// <auto-generated />
using SuperApp.Gateway.Persistence.Entities;
using System;
using SuperApp.Gateway.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SuperApp.Gateway.Persistence.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20260929234830_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gateway")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperApp.Gateway.Persistence.Entities.ProxyCluster", b =>
                {
                    b.Property<string>("Profile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ClusterId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ActivityTimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("HealthCheckEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("HealthCheckIntervalSeconds")
                        .HasColumnType("int");

                    b.Property<string>("HealthCheckPath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("HealthCheckTimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<string>("HttpVersion")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("LoadBalancingPolicy")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("Profile", "ClusterId");

                    b.ToTable("Clusters", "gateway", t =>
                        {
                            t.HasCheckConstraint("CK_Clusters_HealthCheck", "[HealthCheckEnabled] = 0 OR [HealthCheckPath] IS NOT NULL");

                            t.HasCheckConstraint("CK_Clusters_HttpVersion", "[HttpVersion] IS NULL OR [HttpVersion] IN ('1.1','2')");

                            t.HasCheckConstraint("CK_Clusters_LoadBalancing", "[LoadBalancingPolicy] IS NULL OR [LoadBalancingPolicy] IN ('RoundRobin','PowerOfTwoChoices','LeastRequests','Random','FirstAlphabetical')");

                            t.HasCheckConstraint("CK_Clusters_Profile", "[Profile] IN ('bff-web','gateway-mobile')");

                            t.HasCheckConstraint("CK_Clusters_Timeouts", "[ActivityTimeoutSeconds] > 0 AND ([HealthCheckIntervalSeconds] IS NULL OR [HealthCheckIntervalSeconds] > 0) AND ([HealthCheckTimeoutSeconds] IS NULL OR [HealthCheckTimeoutSeconds] > 0)");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ClustersHistory", "gateway");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));

                    b.HasData(
                        new
                        {
                            Profile = "bff-web",
                            ClusterId = "knowledge",
                            ActivityTimeoutSeconds = 30,
                            HealthCheckEnabled = false,
                            HttpVersion = "1.1",
                            LoadBalancingPolicy = "RoundRobin"
                        },
                        new
                        {
                            Profile = "bff-web",
                            ClusterId = "sleepdiary",
                            ActivityTimeoutSeconds = 30,
                            HealthCheckEnabled = false,
                            HttpVersion = "1.1",
                            LoadBalancingPolicy = "RoundRobin"
                        },
                        new
                        {
                            Profile = "gateway-mobile",
                            ClusterId = "knowledge",
                            ActivityTimeoutSeconds = 30,
                            HealthCheckEnabled = false,
                            HttpVersion = "1.1",
                            LoadBalancingPolicy = "RoundRobin"
                        },
                        new
                        {
                            Profile = "gateway-mobile",
                            ClusterId = "sleepdiary",
                            ActivityTimeoutSeconds = 30,
                            HealthCheckEnabled = false,
                            HttpVersion = "1.1",
                            LoadBalancingPolicy = "RoundRobin"
                        });
                });

            modelBuilder.Entity("SuperApp.Gateway.Persistence.Entities.ProxyDestination", b =>
                {
                    b.Property<string>("Profile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ClusterId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DestinationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("Profile", "ClusterId", "DestinationId");

                    b.ToTable("Destinations", "gateway", t =>
                        {
                            t.HasCheckConstraint("CK_Destinations_ClusterAddress", "[Address] LIKE 'http://%.svc.cluster.local%' OR [Address] LIKE 'https://%.svc.cluster.local%'");

                            t.HasCheckConstraint("CK_Destinations_Profile", "[Profile] IN ('bff-web','gateway-mobile')");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("DestinationsHistory", "gateway");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));

                    b.HasData(
                        new
                        {
                            Profile = "bff-web",
                            ClusterId = "knowledge",
                            DestinationId = "knowledge-api",
                            Address = "http://knowledge-api.knowledge.svc.cluster.local:8080"
                        },
                        new
                        {
                            Profile = "bff-web",
                            ClusterId = "sleepdiary",
                            DestinationId = "sleepdiary-api",
                            Address = "http://sleepdiary-api.sleepdiary.svc.cluster.local:8080"
                        },
                        new
                        {
                            Profile = "gateway-mobile",
                            ClusterId = "knowledge",
                            DestinationId = "knowledge-api",
                            Address = "http://knowledge-api.knowledge.svc.cluster.local:8080"
                        },
                        new
                        {
                            Profile = "gateway-mobile",
                            ClusterId = "sleepdiary",
                            DestinationId = "sleepdiary-api",
                            Address = "http://sleepdiary-api.sleepdiary.svc.cluster.local:8080"
                        });
                });

            modelBuilder.Entity("SuperApp.Gateway.Persistence.Entities.ProxyRoute", b =>
                {
                    b.Property<string>("Profile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RouteId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AuthorizationPolicy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("MaxRequestBodySize")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("RateLimiterPolicy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("int");

                    b.HasKey("Profile", "RouteId");

                    b.HasIndex("Profile", "ClusterId");

                    b.HasIndex("Profile", "Path", "Order")
                        .IsUnique();

                    b.ToTable("Routes", "gateway", t =>
                        {
                            t.HasCheckConstraint("CK_Routes_Limits", "([TimeoutSeconds] IS NULL OR [TimeoutSeconds] > 0) AND ([MaxRequestBodySize] IS NULL OR [MaxRequestBodySize] > 0)");

                            t.HasCheckConstraint("CK_Routes_Path", "[Path] LIKE '/%'");

                            t.HasCheckConstraint("CK_Routes_Profile", "[Profile] IN ('bff-web','gateway-mobile')");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("RoutesHistory", "gateway");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));

                    b.HasData(
                        new
                        {
                            Profile = "bff-web",
                            RouteId = "knowledge-api",
                            AuthorizationPolicy = "knowledge",
                            ClusterId = "knowledge",
                            Order = 100,
                            Path = "/api/knowledge/{**rest}",
                            RateLimiterPolicy = "per-user",
                            TimeoutSeconds = 30
                        },
                        new
                        {
                            Profile = "bff-web",
                            RouteId = "sleepdiary-api",
                            AuthorizationPolicy = "sleepdiary",
                            ClusterId = "sleepdiary",
                            Order = 100,
                            Path = "/api/sleepdiary/{**rest}",
                            RateLimiterPolicy = "per-user",
                            TimeoutSeconds = 30
                        },
                        new
                        {
                            Profile = "gateway-mobile",
                            RouteId = "knowledge-api",
                            AuthorizationPolicy = "knowledge",
                            ClusterId = "knowledge",
                            Order = 100,
                            Path = "/api/knowledge/{**rest}",
                            RateLimiterPolicy = "per-user",
                            TimeoutSeconds = 30
                        },
                        new
                        {
                            Profile = "gateway-mobile",
                            RouteId = "sleepdiary-api",
                            AuthorizationPolicy = "sleepdiary",
                            ClusterId = "sleepdiary",
                            Order = 100,
                            Path = "/api/sleepdiary/{**rest}",
                            RateLimiterPolicy = "per-user",
                            TimeoutSeconds = 30
                        });
                });

            modelBuilder.Entity("SuperApp.Gateway.Persistence.Entities.ProxyRouteHost", b =>
                {
                    b.Property<string>("Profile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RouteId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Host")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("Profile", "RouteId", "Host");

                    b.ToTable("RouteHosts", "gateway");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("RouteHostsHistory", "gateway");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("SuperApp.Gateway.Persistence.Entities.ProxyRouteMethod", b =>
                {
                    b.Property<string>("Profile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RouteId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Method")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("Profile", "RouteId", "Method");

                    b.ToTable("RouteMethods", "gateway", t =>
                        {
                            t.HasCheckConstraint("CK_RouteMethods_Method", "[Method] IN ('GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS')");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("RouteMethodsHistory", "gateway");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("SuperApp.Gateway.Persistence.Entities.ProxyRouteTransform", b =>
                {
                    b.Property<string>("Profile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RouteId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Profile", "RouteId", "Order");

                    b.ToTable("RouteTransforms", "gateway", t =>
                        {
                            t.HasCheckConstraint("CK_RouteTransforms_Fields", "([Kind] IN ('PathRemovePrefix','PathPrefix','PathPattern') AND [Value] IS NOT NULL AND [Name] IS NULL) OR ([Kind] IN ('RequestHeaderSet','ResponseHeaderSet') AND [Name] IS NOT NULL AND [Value] IS NOT NULL) OR ([Kind] IN ('RequestHeaderRemove','ResponseHeaderRemove') AND [Name] IS NOT NULL AND [Value] IS NULL)");

                            t.HasCheckConstraint("CK_RouteTransforms_Kind", "[Kind] IN ('PathRemovePrefix','PathPrefix','PathPattern','RequestHeaderSet','RequestHeaderRemove','ResponseHeaderSet','ResponseHeaderRemove')");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("RouteTransformsHistory", "gateway");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));

                    b.HasData(
                        new
                        {
                            Profile = "bff-web",
                            RouteId = "knowledge-api",
                            Order = 0,
                            Kind = "PathRemovePrefix",
                            Value = "/api/knowledge"
                        },
                        new
                        {
                            Profile = "bff-web",
                            RouteId = "sleepdiary-api",
                            Order = 0,
                            Kind = "PathRemovePrefix",
                            Value = "/api/sleepdiary"
                        },
                        new
                        {
                            Profile = "gateway-mobile",
                            RouteId = "knowledge-api",
                            Order = 0,
                            Kind = "PathRemovePrefix",
                            Value = "/api/knowledge"
                        },
                        new
                        {
                            Profile = "gateway-mobile",
                            RouteId = "sleepdiary-api",
                            Order = 0,
                            Kind = "PathRemovePrefix",
                            Value = "/api/sleepdiary"
                        });
                });

            modelBuilder.Entity("SuperApp.Gateway.Persistence.Entities.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SessionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("SessionId");

                    b.HasIndex("Subject");

                    b.ToTable("Sessions", "gateway");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", "gateway");
                });

            modelBuilder.Entity("SuperApp.Gateway.Persistence.Entities.ProxyDestination", b =>
                {
                    b.HasOne("SuperApp.Gateway.Persistence.Entities.ProxyCluster", null)
                        .WithMany()
                        .HasForeignKey("Profile", "ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SuperApp.Gateway.Persistence.Entities.ProxyRoute", b =>
                {
                    b.HasOne("SuperApp.Gateway.Persistence.Entities.ProxyCluster", null)
                        .WithMany()
                        .HasForeignKey("Profile", "ClusterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SuperApp.Gateway.Persistence.Entities.ProxyRouteHost", b =>
                {
                    b.HasOne("SuperApp.Gateway.Persistence.Entities.ProxyRoute", null)
                        .WithMany()
                        .HasForeignKey("Profile", "RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SuperApp.Gateway.Persistence.Entities.ProxyRouteMethod", b =>
                {
                    b.HasOne("SuperApp.Gateway.Persistence.Entities.ProxyRoute", null)
                        .WithMany()
                        .HasForeignKey("Profile", "RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SuperApp.Gateway.Persistence.Entities.ProxyRouteTransform", b =>
                {
                    b.HasOne("SuperApp.Gateway.Persistence.Entities.ProxyRoute", null)
                        .WithMany()
                        .HasForeignKey("Profile", "RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
