using Knowledge.Domain.Collections;
using Knowledge.Domain.Materials;
using SuperApp.Framework.Domain.Results;
using SuperApp.Framework.Domain.ValueObjects;

namespace Knowledge.Domain.Categories;

/// <summary>
/// Identifier of a category (<see cref="Knowledge.Domain.Categories.Category"/>), also used to assign materials and collections to categories.
/// </summary>
/// <remarks>
/// <para>
/// A hand-written strongly typed identifier (ADR-0023) wrapping a <see cref="Guid"/>. It exists so that the compiler rejects
/// mix-ups such as passing a <see cref="CollectionId"/> where a <see cref="MaterialId"/> is expected; all Knowledge IDs are
/// <see cref="Guid"/>s underneath and would otherwise be interchangeable.
/// </para>
/// <para>
/// Generated by <see cref="Knowledge.Domain.Categories.Category.Create"/>; referenced from <see cref="Knowledge.Domain.Materials.MaterialCategory"/> and <see cref="Knowledge.Domain.Collections.CollectionCategory"/>. Those references are not enforced by the aggregates; the command handler checks them with <see cref="Knowledge.Domain.Categories.ICategoryRepository.AllExistAsync"/>.
/// </para>
/// <para>
/// Commands and the HTTP API carry the raw <see cref="Guid"/>; handlers convert it with <see cref="Create(Guid)"/>. EF Core,
/// JSON and OpenAPI mappings come from the <c>SuperApp.Framework</c> conventions, no per-type mapping code is needed.
/// Never create an instance with <c>default</c> or <c>new()</c> (analyzer APP002 rejects it): that yields an empty GUID.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// // SetMaterialCategoriesHandler: parse untrusted GUIDs, then check existence
/// var parsedIds = command.CategoryIds.Distinct().Select(CategoryId.Create).ToList();
/// var categoryIds = parsedIds.Where(id =&gt; id.IsSuccess).Select(id =&gt; id.Value).ToList();
/// if (categoryIds.Count != parsedIds.Count || !await categories.AllExistAsync(categoryIds, cancellationToken))
/// {
///     return CategoryErrors.UnknownCategories;
/// }
/// </code>
/// </example>
public readonly record struct CategoryId : IStronglyTypedId<CategoryId, Guid>
{
    private CategoryId(Guid value) => Value = value;

    /// <inheritdoc />
    public Guid Value { get; }

    /// <inheritdoc />
    public static CategoryId New() => new(Guid.CreateVersion7());

    /// <summary>Creates the identifier from an untrusted <see cref="Guid"/> (command data, route values).</summary>
    /// <param name="value">The raw identifier; must not be <see cref="Guid.Empty"/>.</param>
    /// <returns>
    /// The identifier, or a validation error <c>knowledge.category.invalid_id</c> when <paramref name="value"/> is <see cref="Guid.Empty"/>.
    /// The method does not check that the referenced object exists; that is the repository's job.
    /// </returns>
    public static Result<CategoryId> Create(Guid value) =>
        value == Guid.Empty ? Error.Validation("knowledge.category.invalid_id", "Niepoprawny identyfikator kategorii.") : new CategoryId(value);

    /// <inheritdoc />
    public static CategoryId FromTrusted(Guid value) => new(value);

    /// <summary>Returns the GUID in its default format, so that logs and interpolated strings show the value instead of the type name.</summary>
    /// <returns>The wrapped <see cref="Guid"/> formatted with <see cref="Guid.ToString()"/>.</returns>
    public override string ToString() => Value.ToString();
}
