{{- if .Values.discovery.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "superapp-docs.fullname" . }}
  labels:
    {{- include "superapp-docs.labels" . | nindent 4 }}
{{- end }}
