using SuperApp.Framework.Application.Events;
using Knowledge.Application;
using Knowledge.Application.Content;
using Knowledge.Application.Content.Blocks;
using Knowledge.Application.Features.Collections.CreateCollection;
using Knowledge.Application.Features.Collections.GetCollection;
using Knowledge.Application.Features.Collections.SetCollectionItems;
using Knowledge.Application.Features.Materials.CreateMaterial;
using Knowledge.Application.Features.Materials.GetMaterial;
using Knowledge.Application.Features.Materials.ReplaceMaterialContent;
using Knowledge.Domain.Materials;
using Knowledge.Domain.Materials.Content;
using Knowledge.Infrastructure.Persistence.Write;
using Knowledge.IntegrationTests.Infrastructure;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.Extensions.DependencyInjection;
using SuperApp.Framework.Testing;

namespace Knowledge.IntegrationTests;

/// <summary>
/// Positions of collection items and text spans are set by the domain, not generated by the database (migration
/// <c>FixOwnedPositionKeys</c>): several items and several spans per block are saved and read back in order.
/// </summary>
[Trait("Category", "Integration")]
[Collection(PipelineCollection.Name)]
public sealed class OwnedPositionTests(ServiceFixture fixture)
{
    [Fact]
    public async Task Block_with_several_spans_is_saved_and_read_in_order()
    {
        fixture.ActWith(KnowledgeScopes.CatalogWrite, KnowledgeScopes.CatalogRead);
        var material = ResultAssert.Success(await fixture.SendAsync(new CreateMaterial(MaterialType.Article, "Wiele fragmentów", null, null, null)));
        ContentBlockDto[] content = [new ParagraphBlockDto([new SpanDto("Zasypiaj "), new SpanDto("o stałej", [TextMarks.Bold]), new SpanDto(" porze.")])];

        Assert.True((await fixture.SendAsync(new ReplaceMaterialContent(material, content))).IsSuccess);
        Assert.True((await fixture.SendAsync(new ReplaceMaterialContent(material, content))).IsSuccess);

        var read = ResultAssert.Success(await fixture.SendAsync(new GetMaterial(material)));
        var paragraph = Assert.IsType<ParagraphBlockDto>(Assert.Single(read.Content));
        Assert.Equal(["Zasypiaj ", "o stałej", " porze."], paragraph.Text.Select(span => span.Text));
    }

    [Fact]
    public async Task Collection_with_several_items_is_saved_reordered_and_read_in_order()
    {
        fixture.ActWith(KnowledgeScopes.CatalogWrite, KnowledgeScopes.CatalogRead);
        var first = ResultAssert.Success(await fixture.SendAsync(new CreateMaterial(MaterialType.Article, "Pierwszy", null, null, null)));
        var second = ResultAssert.Success(await fixture.SendAsync(new CreateMaterial(MaterialType.Article, "Drugi", null, null, null)));
        var third = ResultAssert.Success(await fixture.SendAsync(new CreateMaterial(MaterialType.Article, "Trzeci", null, null, null)));
        var collection = ResultAssert.Success(await fixture.SendAsync(new CreateCollection("Kolejność", null)));

        Assert.True((await fixture.SendAsync(new SetCollectionItems(collection, [first, second, third]))).IsSuccess);
        Assert.True((await fixture.SendAsync(new SetCollectionItems(collection, [third, first]))).IsSuccess);

        var read = ResultAssert.Success(await fixture.SendAsync(new GetCollection(collection)));
        Assert.Equal([third, first], read.Materials.Select(material => material.Id));
    }

    [Fact]
    public async Task Migration_keeps_existing_items_and_renumbers_their_positions()
    {
        await using var scope = fixture.Services.CreateAsyncScope();
        var source = scope.ServiceProvider.GetRequiredService<KnowledgeWriteDbContext>().Database.GetConnectionString();
        var connectionString = new SqlConnectionStringBuilder(source) { InitialCatalog = $"knowledge_migration_{Guid.NewGuid():N}" }.ConnectionString;
        var options = new DbContextOptionsBuilder<KnowledgeWriteDbContext>()
            .UseSqlServer(connectionString, sql => sql.MigrationsHistoryTable("__EFMigrationsHistory", KnowledgeWriteDbContext.SchemaName))
            .Options;
        await using var db = new KnowledgeWriteDbContext(options, scope.ServiceProvider.GetRequiredService<IDomainEventDispatcher>());
        var migrator = db.GetService<IMigrator>();
        var cancellationToken = TestContext.Current.CancellationToken;

        try
        {
            await migrator.MigrateAsync("20260929233807_Initial", cancellationToken);
            var collectionId = Guid.NewGuid();
            Guid[] materials = [Guid.NewGuid(), Guid.NewGuid()];
            await db.Database.ExecuteSqlAsync(
                $"""
                INSERT INTO [knowledge].[Collections] ([Id], [Title], [Status], [CreatedAt], [UpdatedAt]) VALUES ({collectionId}, N'Stara', N'Draft', SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET());
                INSERT INTO [knowledge].[CollectionItems] ([CollectionId], [MaterialId]) VALUES ({collectionId}, {materials[0]});
                INSERT INTO [knowledge].[CollectionItems] ([CollectionId], [MaterialId]) VALUES ({collectionId}, {materials[1]});
                """,
                cancellationToken);

            await migrator.MigrateAsync(cancellationToken: cancellationToken);

            var positions = await db.Database
                .SqlQuery<int>($"SELECT [Position] AS [Value] FROM [knowledge].[CollectionItems] WHERE [CollectionId] = {collectionId} ORDER BY [Position]")
                .ToListAsync(cancellationToken);
            var ordered = await db.Database
                .SqlQuery<Guid>($"SELECT [MaterialId] AS [Value] FROM [knowledge].[CollectionItems] WHERE [CollectionId] = {collectionId} ORDER BY [Position]")
                .ToListAsync(cancellationToken);
            Assert.Equal([0, 1], positions);
            Assert.Equal(materials, ordered);
        }
        finally
        {
            await db.Database.EnsureDeletedAsync(cancellationToken);
        }
    }
}
